### ISSUE TITLE
SSID password and MQTT password readable

### ISSUE THREAD

**Issue by kroon040** [revk/ESP32-Faikin#103]
Hi,

It doesn't feel right that if someone breaks into my network and finds the webinterface , he can simply read the password for the ssid and mqtt. Is it possible that it is not seen? for example with asterisks.

**Comment by revk** [comment]
There is a setting (via MQTT) to disable that, yes.

Do you have MQTT set up.

The setting is, I think, webserver, which you can set to 0, 1, or 2.

You want 1 I expect.

**Comment by revk** [comment]
You can turn off the access to passwords and settings (as above), so I'll close this issue.

There is, indeed, a valid discussion on better ways to approach this.
