### ISSUE TITLE
Work With ESP-Home

### ISSUE THREAD

**Issue by fantasiataiwan** [revk/ESP32-Faikin#110]
Can Faikin work with ESP-Home?

**Comment by revk** [comment]
The hardware is just an ESP32 with serial at right levels. If esp home can run on ESP32 and handle inverted UART to a Daikin then I see no reason why not. You would need a suitable serial lead to load code (see Tasmotiser).

**Comment by joshbenner** [comment]
I use [esphome-daikin-s21](https://github.com/joshbenner/esphome-daikin-s21) on a Faikin board. README there includes the config I use for dealing with the serial invert.

**Comment by fantasiataiwan** [comment]
I tried to flash esphome and your v1.bin but it's not working.
I haven't see the hotspot SSID maybe I have something wrong haha.

**Comment by revk** [comment]
The board is pretty generic, so maybe raise this with the esphome designers. The schematic for this board is published.

**Comment by shikousa** [comment]
@revk What is the reason that your board is inverting the TTL-UART?

**Comment by revk** [comment]
The reason is down to the fact the Daikin works at 5V. Using a FET each way is an inexpensive solution to allow that to work with the 3.3V of the ESP32. It has the side effect of inverting, but as the ESP32 has hardware tx/rx invert options it is no problem.

**Comment by shikousa** [comment]
I was thinking of an ADUM1201 to also get isolation. There is the 3,3V from the ESP32 for VDD1 of the ADUM1201. On PIN1 of the S21 socket is there always 5V? This would be for VDD2 of the ADUM1201. Then the ADUM1201 might also be an approach, what do you think?

**Comment by revk** [comment]
Most 3.3-5V converters expect a 5V supply. The issue is the Daikin units and wiring vary so I can't be sure to always have a 5V available. It does seem the signal to the Daikin does have internal pull up though, so this circuit has been found to work well.

**Comment by shikousa** [comment]
In your schmatic you take PIN1 for having the 5V for PIN3 (RX). What if these 5V are not available?

**Comment by revk** [comment]
Yes, that is just in case. What seems to be the case is the data to the Daikin always has a pull up, so just the FET pulls down. And sometimes there is 5V (not on my units, for example). By having both there is a good chance of it working with all models (that have S21 or X50A). So far it seems to be working well.

**Comment by shikousa** [comment]
Thanks. It would be interesting how other gateways have solved this. The Zennio KLICDDv3 has KNX, actually it should have a galvanic isolation.

**Comment by revk** [comment]
I did not consider isolation necessary, but I understand some Daikin have non isolated S21 like ports but they then sell an adaptor to isolate. It would obviously be more complex to add isolation.

**Comment by shikousa** [comment]
The power consumption of an ESP32 is pretty high, recommended is a supply with 500mA. Do you know if PIN4 (>5V) can deliver this long term.

**Comment by revk** [comment]
My understanding is that the 5V cannot deliver the power needed.

**Comment by shikousa** [comment]
Yes, but you are using PIN4 with e.g. 12V. Do you know what this PIN can deliver?

**Comment by revk** [comment]
We have had no problem with the 12V (often reported and 14V, or some such) powering the ESP32.
