### ISSUE TITLE
Please make the Comfort Fan Mode and Streamer available in Home Assistant

### ISSUE THREAD

**Issue by wurmtal868** [revk/ESP32-Faikin#140]
Hello revk,
First of all, thank you for developing the Faikin Module :-)
After successful integration and testing the first module, I ordered 5 more for my remaining indoor units. 

In order to leave the Daikin cloud for good, I would be happy if could add the comfort fan and streamer mode to Home Assistant.
Both are already supported in your Web frontend.

The icing of the cake, would be an option to control the 3D sensor of my Perfera units. 
This only supported trough the IR remote, in the Onnecta App it's not available.

Regards Thomas

**Comment by revk** [comment]
I thought we had these, but I'll look again.

Anything not in their app is probably not in S21 so unlikely we can support it either.

**Comment by revk** [comment]
OK, happy to add to HA, if you can find what the necessary HA config is for these. Then I can add to the config we send and provide the status/commands needed.

**Comment by wurmtal868** [comment]
The HACS cloud integration has added a button panel to the thermostat card.
![image](https://github.com/revk/ESP32-Faikin/assets/32965910/458aa28f-0edb-421b-a5d5-585c4eb95b6c)
That will do it.

**Comment by revk** [comment]
Oh, interesting, that looks useful. I don't suppose you can find the JSON config needed for that?

**Comment by wurmtal868** [comment]
Sorry I'm a newbie in Home Assistant. 
I'm just happy that my indoor unit popped up automatically under MQTT after initial setup. 

Eventually someone else reading this thread can help?

**Comment by revk** [comment]
I may be able to find something in google... I don't use HA myself, so have had to rely on a lot of contributions for these features.

**Comment by wurmtal868** [comment]
For the comfort mode it would make sense adding it to the fan swing menu, because it supersedes the h/v modes.
![image](https://github.com/revk/ESP32-Faikin/assets/32965910/6b68a8b4-3c4d-415d-ad9f-d069b448afdc)

**Comment by revk** [comment]
Ah, OK, that may be possible...

**Comment by revk** [comment]
OK issued a change to add to swing settings, please can you test that?

**Comment by wurmtal868** [comment]
It's working 
![image](https://github.com/revk/ESP32-Faikin/assets/32965910/962115bd-a890-44ce-8359-e6aa1df05365)

Thanks a lot!

**Comment by revk** [comment]
OK if we work out *streamer* controls JSON for HA, I'll add that. I'll close ticket for now until we have that.
