### ISSUE TITLE
[BUG] Changing MQTT Prefix for settings probably not working

### ISSUE THREAD

**Issue by sam-m7** [revk/ESP32-Faikin#151]
**Faikin hardware**
Purchased from Amazon.

**Daikin hardware**
Currently connected to an external power supply. Waiting for the Daikin Adapter cable to arrive, but wanted to check out the device.

**Describe the bug**
I've set all the MQTT Prefixes to "faikin/<default>". <default> being the standard value, like "error", "setting" etc. 
This worked for "state" and "error" or at least the module is sending it's status messages to the changed topic now. But unfortunately sending an empty message to "faikin/setting/<hostname>" doesn't send the current settings back anymore. The old path "setting/<hostname>" doesn't work either. I guess this is a bug, at least if I didn't make a typo...

**To Reproduce**
1. Sending a MQTT message with a JSON like 
{
  "prefix": {
    "error": "faikin/error",
    "setting": "faikin/setting",
    ....
  }
}
to setting/<hostname>

I'm not sure if it was exactly like this, since I don't see the settings anymore. But I've just copied the JSON an empty "setting/<hostname>" message returned, removed everything except the MQTT Prefixes part and added "faikin/" as a prefix to every entry.

2. Try to get the current settings using the new MQTT Topic by sending an empty message to the new topic.

**Expected behavior**
Current settings should be send by the module to "faikin/setting/<hostname>"

**Additional context**
I haven't found a way to reset all the setting back to the defaults using the web front end. Is there a way to do this? Or do I have to erase the flash using a programmer and re-flash the module? Also I've tried to revert it somehow by trying to send the old MQTT topic for setting, but so far this wasn't successful.

**Comment by revk** [comment]
Ah, it splits the topic and then compares, so won't match `faikin/error` as an error prefix, as it will see `faikin` as the prefix. I have updated the manual for my library for that now.

I suspect the only way is erasing the settings in flash, they are 3F0000-3FFFFF in flash.
