### ISSUE TITLE
[BUG] Commands are ignored if they are sent together with an Env command

### ISSUE THREAD

**Issue by ckvsoft** [revk/ESP32-Faikin#157]
If I use ENV as an mqtt message in Commands, all other parameters in this JSon are ignored. I then have to send this separately, but then the Env display stops until an Env command comes again

Faikin-S1-PICO: 4dfbddd 2023-11-18T12:22:21

**Comment by revk** [comment]
Hmm, very likely. I'll take a look in the morning.

**Comment by revk** [comment]
Thanks, will look

**Comment by revk** [comment]
My guess is that the issue is "target" not "env". I'll take another look. Thanks.

**Comment by ckvsoft** [comment]
Thanks, that works now
