### ISSUE TITLE
[BUG] Firmware doesn't work with the latest version of the BLE thermostat sensors

### ISSUE THREAD

**Issue by andreas-bulling** [revk/ESP32-Faikin#169]
I upgraded the thermostat sensors that I've been using with the Faikin module to the latest firmware (v4.5) that supports/switches to BTHome v2: https://github.com/pvvx/ATC_MiThermometer/releases/tag/v4.5

Since then, the sensor readings from these sensors are not shown in the Faikin web interface anymore.

![image](https://github.com/revk/ESP32-Faikin/assets/377856/0af5f2c8-4bb9-4afe-a13e-d00faa7e3e18)

**Comment by revk** [comment]
I'll look and see if it can support that.

**Comment by revk** [comment]
I don't have a set up to test this, but I have added v2 temp/humidity now, so try latest code.

**Comment by andreas-bulling** [comment]
Done (version ba6fce4) - still doesn't work unfortunately :/

**Comment by revk** [comment]
Just to check, you have set it as unencrypted, yes?

I'll have to set up a test here. I was going from the spec, which should have worked.

But should not be too hard to sort.

**Comment by revk** [comment]
I have finally found my spare BLE temp sensors, and flashed, and set to BT Home v2, so starting testing now.

**Comment by revk** [comment]
OK, I believe I have it now, please test latest code.

**Comment by Elwell** [comment]
Can I test this with a stand-alone faikin board (powered on the bench) as I
have a cluster of BTHome v2 temp/hum sensors within range?
Happy to give it a go if it's of help

**Comment by revk** [comment]
You should be able to, yes.

**Comment by Elwell** [comment]
Finally installed it properly :-)  - Currently running Faikin-S1-PICO: d5965b6 2023-12-19T08:53:51
and can confirm that sadly it's not seeing either of the 2 nearby BLE sensors that _are_ being picked up by a T-Internet-POE board and sent to Home Assistant via esphome/bluetooth_proxy.

Telink flasher is showing the nearest device as
```
Status: Hardware Version: LYWSD03MMC B1.4, Software Version: 4.6
Vbat: 2811 mV , Temp: 19.28°C, Humi: 57.77%, ID: 156, Reed switch counter: 0, flg: 0x0F:r1/t1
```

**Comment by revk** [comment]
Well the good news is that I am an idiot, after testing the update to the library I missed pushing the commit, so the change is not in the Faikin code. Issuing new code right now.

**Comment by Elwell** [comment]
That looks better, Ta!

**Comment by Elwell** [comment]
That looks better! Ta!
<img width="448" alt="Screenshot 2023-12-19 at 11 01 50 pm" src="https://github.com/revk/ESP32-Faikin/assets/209107/79815817-7f71-4bcf-a011-4ef690025238">
<img width="275" alt="Screenshot 2023-12-19 at 11 01 21 pm" src="https://github.com/revk/ESP32-Faikin/assets/209107/12f09d27-5211-4f2a-a3e2-d2794411c406">

**Comment by revk** [comment]
Good

**Comment by andreas-bulling** [comment]
Works also for me. Thanks for the super quick fix!
