### ISSUE TITLE
[FEATURE] Manual Fan Speed Indoor Unit

### ISSUE THREAD

**Issue by tobibrnjs** [revk/ESP32-Faikin#175]
**Daikin hardware**
ATXF60A via S21 Faikin ESP32 Board from Amazon

**Is your feature request related to a problem? Please describe.**
I got my new Aircon Unit last week and I’m very  disappointed about the noise the inner unit makes. When I turn the unit on, for one minute it turns with about 250 rpm. The noise level is absolutely okay at this point. But even on Fan Level 1 and Night Mode, the fan spins with about 750 rpm and the unit is clearly noticeable. If it is not possible to turn down the noise it makes, the unit has to be removed… 

**Describe the solution you'd like**
It would be nice if it is possible to manually set the fan speed of the inner unit, or changing the fan levels to individual rpm‘s.

**Comment by revk** [comment]
S21/X50A allows a small number of fan speed settings, such as 1-3 or 1-5 and auto and maybe quiet, though quite mode seems to lack a specific S21 response. That is all that can be sent as far as I know...

If there is a message that does what you want and you find any details I'll be happy to add. But I suspect there is not one.
