### ISSUE TITLE
[FEATURE] Alternatives for OOS parts at JLC?

### ISSUE THREAD

**Issue by mike-yowen** [revk/ESP32-Faikin#185]
First off, thank you for all the work on this! In going through the process to order from JLC it appears they are currently out of stock or have very low stock of the following items:

- [D2, D3] GOODWORK ES05D1MC10 (DFN1006-2(SOD-882) TVS ROHS)
- [U3] Shanghai Mingda Microelectronics MD8942 (Step-down type 4V~36V SOT-23-6 DC-DC Converters ROHS)

1. Can you recommend any alternatives that will work in-place or should I wait until all of the original components are in stock?
2. I get a warning that "J2 designator don't exist in the BOM file." - is that expected? 
3. Is [J3] "USB-PROG" an actual component? It is matching to "HOOYA USB-111-B-SU" but that doesn't look like the production boards on Amazon.

![image](https://github.com/revk/ESP32-Faikin/assets/10055220/4f38a00f-e273-4322-bae8-7ff11f4001db)

Thanks again!

**Comment by revk** [comment]
The errors look odd. I'll recheck. There are non real parts like USB PROG. I thought those were all fixed?!

As for parts, you may be able to find alternatives. I have pre purchased the ones on the parts list, so have been able to order with no problems.

**Comment by revk** [comment]
Ok checked, both of those are just pads, and on the bottom, so I would not have spotted as I don't do assembly of the bottom as it had no parts, but I have cleaned up the BOM/positions file anyway now.

**Comment by inuyasha6473** [comment]
@mike-yowen Before I start my search I thought I would see if you were able to successfully locate replacements for the 2 short components?
