### ISSUE TITLE
[FEATURE] Provide a way to change tmin default in auto mode

### ISSUE THREAD

**Issue by ako-sxt** [revk/ESP32-Faikin#188]
**Daikin hardware**
S21 FTXM20R2V1B

**Is your feature request related to a problem? Please describe.**
The minimum temperature which is set on the aircon is 16° set by auto mode. This leads to my problem in Heating mode that the aircon is sometimes starting even if the temperature is 18 or more. Currently it is hardcoded to 16°

**Describe the solution you'd like**
Provide a way to set a lower default for tmin either by mqtt or setting.

**Describe alternatives you've considered**
I currently switched of auto mode and set the temp to something less than 16°, that works. 
But this could not use my BLE sensor temperature which is more accurate.

**Comment by revk** [comment]
`setting/Faikin/tmin X`

<img width="858" alt="Screenshot 2024-01-17 at 09 43 10" src="https://github.com/revk/ESP32-Faikin/assets/996983/0dcbe09b-6a5b-4f19-b87e-fc34ade7cfbb">
