### ISSUE TITLE
[FEATURE] Change fan_modes output text to low, medium, high instead of 1, 2, 3

### ISSUE THREAD

**Issue by BenJamesAndo** [revk/ESP32-Faikin#190]
Currently the fan_modes are listed as
```
fan_modes:
  - auto
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - night
```
In the [2024.1](https://www.home-assistant.io/blog/2024/01/03/release-20241/) release of Home Assistant they added  climate fan mode card feature. This allows you to select the fan mode in an easy drop-down using either the Climate card or Tile card.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/00125968-5968-49f6-89ea-b240273cd4c9)
However it seems to only display values that contain text, nor numbers.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/b0f59a73-81a9-443e-88f9-2810a79a7dd8)

If I go into the additional settings I can still change the fan mode
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/a1d1dcd4-8ba2-4932-a125-a4c6234dcb4f)

Home Assistant has a list of officially supported Names that if used will mean there'll be an icon next to the fan mode. https://developers.home-assistant.io/docs/core/entity/climate/#fan-modes

So if there was a way to re-name the values from 1 to slow etc. that'd be amazing.

**Comment by revk** [comment]
Does your device have 5 levels, that is what I think S21 allows, so not sure of names to use as they have low/medium/high, not 5 levels.

**Comment by BenJamesAndo** [comment]
Ah yes mine does have 5, I just used 3 as an example. Perhaps the following could work
```
low
medium
medium_high
high
max
```

**Comment by BenJamesAndo** [comment]
I have an AC with [SmartIR](https://github.com/smartHomeHub/SmartIR) and it has these options.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/56f02d30-dc8e-4ef1-85ff-9192fd6bcf2e)

**Comment by revk** [comment]
I'll issue a change, just a tad worried in case it upsets other people... Can you test ASAP and confirm it works better with HA than current version.

**Comment by BenJamesAndo** [comment]
Hmm kinda strange. Dropdown is blank now.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/3494a39d-8c97-4d01-9670-184b436f6d1b)

night, low & medium doesn't work
low medium goes to 1
medium high goes to 3
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/1c32a4a8-770a-4666-90e5-eb77605b4fb0)

**Comment by revk** [comment]
OK changed back issued code 1-5 now.

We need to set you to load test code for this...

`setting/Faikin/outahost excalibur.belmont.cymru`

**Comment by revk** [comment]
OK set `otahost` as above, and let me know.

**Comment by iancoop** [comment]
I happened to see this, and updated. The dropdown worked ok here. On 18 Jan 2024, at 21:40, RevK ***@***.***> wrote:﻿
OK set otahost as above, and let me know.

**Comment by BenJamesAndo** [comment]
K I've switched to the test code branch and updated. So yeah turns out if I just re-enable the fan modes then even the numbers show up for me now. I think what I did was when I first set up the Faikin AC I duplicated the UI card and that would have inherited different fan modes, hence why the 1-5 didn't show up. So turns out I was wrong and Home Assistant can in fact show numbers as fan speeds in a dropdown.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/fa6660bb-bb28-4414-bfa5-c5fff6575125)

**Comment by revk** [comment]
OK I'll make a change and you can try, first, what build type is it (bottom of settings page on web interface)

**Comment by BenJamesAndo** [comment]
Faikin-S3-MINI-N4-R2: 41d6a4b 2024-01-18T10:33:28

**Comment by revk** [comment]
I could not see `FAN_LOW` in the link you provided, happy to try those, where did you find them?

**Comment by revk** [comment]
I have made a build with `FAN_LOW` etc, they may not work to make changes yet, but can you check HA is happy with them?

**Comment by BenJamesAndo** [comment]
I saw `FAN_LOW` at https://developers.home-assistant.io/docs/core/entity/climate/#fan-modes

Just updated and this is what I see now
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/a97e6bbb-6764-4e3d-9c8b-980734f0af66)

**Comment by BenJamesAndo** [comment]
Switching fan modes doesn't work and this is the error log in Home Assistant
2024-01-18 21:31:17.223 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid fan_modes mode: 1
2024-01-18 21:31:17.224 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'target' when rendering '{{value_json.target}}'

Seems like it still thinks it's 1 instead of FAN_LOW

**Comment by revk** [comment]
OK let me try and join the dots here...

**Comment by revk** [comment]
OK try and upgrade now

**Comment by BenJamesAndo** [comment]
K so it still displays as FAN_LOW as before but when switching it does in fact change the fan mode.

**Comment by revk** [comment]
Are you able to see the status we are sending back? It should use the exact names we set?

**Comment by revk** [comment]
I wonder if it should not have `FAN_` on the front?

**Comment by BenJamesAndo** [comment]
Yeah maybe it shouldn't have `FAN_`. Looking through a .json file for SmartIR config and this is how it declares it
```
   "fanModes":[
      "auto",
      "night",
      "low",
      "lowMedium",
      "medium",
      "mediumHigh",
      "high",
      "powerful"
   ],
```

**Comment by revk** [comment]
I have `powerful` as a separate setting (I think it reverts to previous fan, so is not a fan speed itself, but an override).

Anyway, changed to those, try now.

**Comment by BenJamesAndo** [comment]
It works! Thanks so much!
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/2cb38035-03c1-4ecc-8194-d7654e949800)

**Comment by revk** [comment]
OK can you confirm changes to all options work, and if so I'll issue new code on `ota.revk.uk`

**Comment by BenJamesAndo** [comment]
Yup changes to all options work.

**Comment by revk** [comment]
OK new code in 5 mins, change `otahost` back to `ota.revk.uk`.
