### ISSUE TITLE
Floating part in stl file

### ISSUE THREAD

**Issue by mike-yowen** [revk/ESP32-Faikin#200]
There is a floating part in the case stl file. Is this an artifact or actually something that should be printed?

https://github.com/revk/ESP32-Faikin/blob/main/PCB/Faikin/Faikin.stl

![image](https://github.com/revk/ESP32-Faikin/assets/10055220/62d0429a-be0a-46c6-b176-12f143c1d81f)

**Comment by revk** [comment]
It is an artefact, don't print. I need to work out how to eliminate it.
