### ISSUE TITLE
Demand

### ISSUE THREAD

**Issue by ckvsoft** [revk/ESP32-Faikin#210]
What will Demand do?
I set it to 0% Daikin goes down but when i set i return  to 100% nothing will be changed,.
Daikin not heating

**Comment by revk** [comment]
Well, it sends the command on to the Daikin. 100% should get it going again.

**Comment by openKimchi** [comment]
for me it is always at 99%. If I set it to 40%, it returns to 99% after a while.

**Comment by ckvsoft** [comment]
I'm not even going to start with that.
What % should be set there? what is done and when?
I tried setting this to 0%. The Daikin is regulated down there. If I set it back to 100% nothing changes. I had to turn off the power to the air conditioning so that it could start heating again.
I have no idea what this setting is for. I don't want this to take on a life of its own,

**Comment by revk** [comment]
I can make it a setting as to whether this is even there. I don't know enough about it. On mine setting 100% works fine. If you can't change it then the daikin is not accepting the change.

**Comment by openKimchi** [comment]
I also have a hot water tank in my system. Since implementing this setting, the interaction between the tank and the other indoor units no longer works satisfactorily.
And as I said, the setting always jumps back to 99% when I set something else.
Please remove this feature or at least enable it to be disabled.

**Comment by revk** [comment]
That makes no sense, if you don't change it we don't change it.

But as it seems to cause some confusion I'll add an option to disable it.

Should be later today.

**Comment by openKimchi** [comment]
I don't think the problem is that I can't change it but that it is always at 99% and the hot water tank has no chance of interrupting. Something like that...

**Comment by openKimchi** [comment]
ok, thx!

**Comment by revk** [comment]
In fact, given that 99% is basically "silly" I can use that to detect that it is model that does not do the same demand control setting.

**Comment by openKimchi** [comment]
There is only one outdoor unit to which you can connect a hot water tank. This is the Daikin 4MWXM52A Multi+
Maybe the problem lies with this outdoor unit.

**Comment by revk** [comment]
OK new code.

1. If it sees 99% it assumes it is silly so does not have demand control
2. Option to turn off demand control (only present if it sees it)
3. Option to load "beta" release s/w
