### ISSUE TITLE
input capacitor on Step-Down

### ISSUE THREAD

**Issue by stonewalljones** [revk/ESP32-Faikin#212]
Is C1591 the correct part here?
C1591 is CL10B104KB8NNNC which is a 100nf(.1uf) 50v cap.

I ordered DIY board from pcbway with the c1591 part and they aren't powering on when connected to my AC units.

https://github.com/revk/ESP32-Faikin/blob/main/PCB/Faikin/production/bom.csv#L6

**Comment by revk** [comment]
That is an odd discrepancy, but all of the boards I have made have the same discrepancy and are using C1591. That seems to suggest 1.uF is adequate.
