### ISSUE TITLE
[BUG] powerful mode is changing from on to off on its own once enabled.

### ISSUE THREAD

**Issue by turbolooser** [revk/ESP32-Faikin#215]
When I switch on powerful mode then its changing back to off and on and vice versa (flipping) every couple of seconds

<img width="461" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/115738363/fcd19c6b-2e0c-45e7-bb5a-e9fabb6f0193">

**Comment by revk** [comment]
Ok that is weird, I am away for a few days, but I'll see if I can reproduce it when I get back.

**Comment by MuzzaMcD** [comment]
I believe the black Asterix next to the Set 28C slider control indicates that you are in Faikin Auto mode. (?)
Not sure that trying to also tell the unit to enforce 'Powerful Mode' is logical.
I see that when Faikin Auto mode is Enabled the message " ✷ Automatic control means some functions are limited" is displayed.
In other words, on the one hand the Faikin Auto setting is trying to perform gradual controls to keep your unit at a specific set temperature and in a very specific range +-1c (?)  but the 'Powerful' request button is saying 'all in' (max thrust from the engine room'), forget set temperature just pump as much heat (or cool) as possible now.

**Comment by revk** [comment]
Even so, it should not be flipping continuously. Does you aircon have *powerful*, it seems some settings are used for different things on different models.

Failing that, enabling `debug` and logging MQTT messages may give a clue what is happening.

**Comment by revk** [comment]
If you can get me a dump, I'll re-open. I could not reproduce it here.
