### ISSUE TITLE
Home Assistant - Consistency to official Daikin Integration

### ISSUE THREAD

**Issue by urbozz** [revk/ESP32-Faikin#22]
The Faikin now just appears in HA with MQTT. Nice!

Few Suggestions that would be nice to have to keep consistency with regards to icons and descriptions with other HA Climate & Daikin integration (some screenshots of official Daikin attached). 

Also would be nice to select Sienet as Fan mode.

Climate Entity: mdiThermostat
Temperature Entities: mdiThermometer

![Screenshot 2023-03-21 at 17 16 48](https://user-images.githubusercontent.com/26883465/226690320-79914cf5-7ce1-48ff-8139-ed2ec973c4e3.png)
![Screenshot 2023-03-21 at 17 17 57](https://user-images.githubusercontent.com/26883465/226690327-e9404b56-dcea-4b40-8a5d-a6889d323dba.png)
![Screenshot 2023-03-21 at 17 18 05](https://user-images.githubusercontent.com/26883465/226690332-eff179c9-a6a0-425a-b77a-79039418abfd.png)
![Screenshot 2023-03-21 at 17 18 11](https://user-images.githubusercontent.com/26883465/226690335-cb2c1848-afdf-4f95-ac02-86ba040aa188.png)
![Screenshot 2023-03-21 at 17 18 17](https://user-images.githubusercontent.com/26883465/226690338-c533781a-66b0-4f23-bc95-0eb950a6d9cc.png)

**Comment by revk** [comment]
The fan mode is a problem - the quite/silent/night mode appears to be possible to set but not report - if you find anything in S21 messages that covers this, do let me know.

**Comment by revk** [comment]
If you know the HA JSON config in use in these other cases, can you paste it, that will help work out what changes can be made to be consistent.

**Comment by revk** [comment]
I'll close for now - if you can find the config/JSON for HA for this, I am happy to change.
