### ISSUE TITLE
[BUG] Fan mode "Night" ans "Auto" is not taken over if set in App/Cloud

### ISSUE THREAD

**Issue by miniluma** [revk/ESP32-Faikin#234]
**Describe the bug**
Coming from a defined fan step (1-5): If you set Fan mode to Auto or Night via Remote control or Cloud, Faikin is not taken these values. MQTT and Web Interface keep last fan level.

**Comment by miniluma** [comment]
Set Auto or Night in Faikin works fine.

**Comment by revk** [comment]
If it won't change then it may be the S21 messages are not accepted. A `dump` / `debug` would help.

**Comment by miniluma** [comment]
dump is coming too fast. So I took debug.


Fan 1->2 in cloud
s21_G1
14<4

Fan  2->1
s21_G1
14<3

Fan 1->Night
s21_G1
14<A

Fan Night ->Auto
s21_G1
14<A

Night and Auto comes as 'A'. It's not handled.
![image](https://github.com/revk/ESP32-Faikin/assets/77453740/0bf19059-4063-44a0-aa6b-88e6a81c91f1)

**Comment by revk** [comment]
OK night should show as auto usually as the S21 messages do not seem to include reporting night more. E.g even if you change to night mode from the remote control it will report as auto in the messages.

Are you saying we don't see 'A' as auto?

**Comment by miniluma** [comment]
> Are you saying we don't see 'A' as auto?

Right.
I assume e.g. daikin.fan equals 1 and daikin.fanrpm is 690. And then comes 'A' which is not handled at all..

**Comment by revk** [comment]
Hmm... Yeh, maybe a small hole in the logging there.

**Comment by revk** [comment]
OK I'll make a beta now with a change of logic, try in a few minutes..

**Comment by miniluma** [comment]
Now it goes at least from Fan=1 to Auto. So only night is not correct, but I understand that you don't see this from the S21 message.

**Comment by revk** [comment]
Thanks, yes, annoying.

**Comment by revk** [comment]
We may have found an S21 message, try the latest beta and report back.

**Comment by miniluma** [comment]
> We may have found an S21 message, try the latest beta and report back.

I confirm. Seems to work perfectly. In both directions: Changes made in the app are reflected in Faikin and changes made in faikin show up in the app. Great work!
