### ISSUE TITLE
Cant access local page

### ISSUE THREAD

**Issue by Yasp0** [revk/ESP32-Faikin#252]
It's a bought Faikin from Amazon. Bought it 2nd hand, it's about 1 year old. 

**Daikin hardware**
I use a FTXM42R/RXM. Connected by S21 port. 

**Describe the bug**
The installation went well, I choose a hostname and connected to that hostname. I could control the airco, all good. 

Then I decided to update the firmware by the settings menu. After the reboot message I could not connect to my own chosen woonkamer.local adress or hostname.local

The AP is not visible. The leds blink red when heating or blue when cooling, that seems ok.

Can I maybe reset the Faikin?

EDIT
OK this is weird, now it does respond and I can access the controle page. I tried a dozen of times in like 30 minutes.

**Comment by revk** [comment]
Sounds like the MDNS is not working for some reason, or it is not on WiFI. If not on WiFi it should show as an AP though.

One way is to turn off your WiFi. This should force it to reappear as an access point and allow you to see settings.

But that may not help matters. The other way is to simply access it by its IP not by the `.local` name. Your router should be able to tell you what IPs it has allocated.
