### ISSUE TITLE
[BUG] System is off line on FTXF60D2V1B

### ISSUE THREAD

**Issue by keesvanbemmel** [revk/ESP32-Faikin#255]
Hi!

I ordered a faikin board from Amazon early July '23 (pictures attached) and just got around to installing it in my FTXF60D. I attached it using a self created s21 cable but also with an original one. Both result in the same behavior: the module setup is fine, mqtt and ssid work perfectly, but "System is off line". I also tried an original wifi module on the s21 port and that works as expected.

Is there anyway to debug what is wrong? Coincidentally I will receive 4 new modules this Monday which I ordered for my other units. Perhaps those are new hardware revisions that work with my unit? I read some units expect 5v signals and older revisions of the faikin board do 3.3?

Perhaps there is anything else I could try or this is a known issue with an easy fix?

Cheers!
![PXL_20240302_145424595 MP](https://github.com/revk/ESP32-Faikin/assets/4633876/01e1c0aa-82cb-41ea-92be-ebab19ddf6bd)
![PXL_20240302_145415468 MP](https://github.com/revk/ESP32-Faikin/assets/4633876/5517440b-6a2b-44b5-bd0d-3a747563ff79)

**Comment by revk** [comment]
That looks like the older boards which work on units that are happy with 3.3V, but not all are (both of mine here were fine). The newer boards work by pulling down against a pull up to 5V in the air-con. So yes, very likely to be the issue.

**Comment by keesvanbemmel** [comment]
Ok I'll wait for the new boards then and swap one out, ok if I keep this open until then?

**Comment by keesvanbemmel** [comment]
Just received them, before I test them: in the new Basic Setting UI, the link to the timezones format page seems missing. What format should I set in the timezone?

**Comment by revk** [comment]
I'll check the timezone. The link should be there, weird.
