### ISSUE TITLE
[BUG] Firmware upgrade button gone?!

### ISSUE THREAD

**Issue by andreas-bulling** [revk/ESP32-Faikin#261]
Maybe I am blind but since the last upgrade of the firmware the button to manually upgrade the firmware is gone. It also doesn't appear if I disable the auto upgrade functionality.

Any reason this has been removed or is this a bug?

**Comment by revk** [comment]
Because there is no new code available. It is checking. Though somewhat tempted to put back or say "up to date".

**Comment by revk** [comment]
I have changed it (latest beta), see what you think.
