### ISSUE TITLE
[FEATURE] Switching off depends on outside temperature

### ISSUE THREAD

**Issue by ckvsoft** [revk/ESP32-Faikin#265]
I would like to be able to switch off the air conditioning based on the outside temperature. Or leave the climate switched off between temperature x and temperature y.
Example:

x = 15, y = 25
If the outside temperature is between the two temperatures, there is no need to heat or cool, so the climate can be off.

**Comment by revk** [comment]
Hmm, this may be better as a script/setting in Home Assistant than a feature in Faikin.

Not ruling it out, but seems a tad specific.

**Comment by ckvsoft** [comment]
Ok, but I think it's a bit overkill to have to install HA just because of this feature

**Comment by revk** [comment]
Ok let me understand the feature here.

Who is it dependant on "outside" temperature, and not inside?

Why does outside matter?

**Comment by ckvsoft** [comment]
;-)
Yes outside is the outside temperature.
But you can consider it done. I have added this feature to my thermostat. It now also controls the air conditioning

**Comment by ckvsoft** [comment]
The idea is if the outside temperature has a certain value and the interior doesn't cool down as much or heat up, it's not necessary to have the air conditioning running.
Unfortunately, Daikin regulates this so poorly that it is better to turn it off.
When the fan is set to auto, it runs constantly at 900 revolutions, regardless of whether the temperature is 1 degree or 5 degrees above/below the set temperature

**Comment by revk** [comment]
There is an auto on/off setting in Faikin, based on target temperature. So if within that it will turn off after a period. It does not look at outside temperature, but might be closer to what you want.

For parts of the year here it means my unit is off pretty much all day.
