### ISSUE TITLE
Replace or suppliment the emojis

### ISSUE THREAD

**Issue by trullock** [revk/ESP32-Faikin#292]
Can we either replace the emojis on Faikin's web interface or add a text description of what they mean?

I can't even guess what "hands on head" or "teddy" mean :)

Awesome product otherwise, bought 3 👍

**Comment by revk** [comment]
Hmm, the table cells all have tool tips to explain.

I suspect that is not as obvious on a mobile.

**Comment by revk** [comment]
OK try latest beta, has a new `no.icons` setting.

**Comment by trullock** [comment]
> Hmm, the table cells all have tool tips to explain.
> 
> I suspect that is not as obvious on a mobile.

Ahh on desktop yes there are tooltips, but only on the controls and not on the icons. Instinctively I was hovering the icons to see what they were but nothing happened. Might be worth tooltipping those too?

**Comment by revk** [comment]
Done, try latest beta

**Comment by trullock** [comment]
Lightening turnaround
