### ISSUE TITLE
Thermostat steps Home assistant only in  1.0 celsius steps possible 

### ISSUE THREAD

**Issue by geni0602** [revk/ESP32-Faikin#304]
**Faikin hardware**
self made esp32 Wroom

**Daikin hardware**
S21 
Daikin Perfera FTXM50R2V1B
Home Assistant 2024.4.0
**Describe the bug**
When I am setting the temperature over HA, the thermostat is going only in 1.0 Steps celsius. In the faikin webUI it is possible to set the target temp in 0.5 step celsius. The Thermostat in HA does not shows the target temp values with 0.5, even it was sent with x.5 over mqtt . When I set target temp for example to 22.5 HA Thermostat is showing 23. Never the less, you can see the correct target temp in the device overview
<img width="323" alt="Bildschirmfoto 2024-04-17 um 14 47 48" src="https://github.com/revk/ESP32-Faikin/assets/62853417/70ca386f-b65d-429f-bd4e-a48682582585">
<img width="554" alt="Bildschirmfoto 2024-04-17 um 14 51 59" src="https://github.com/revk/ESP32-Faikin/assets/62853417/8e47853e-a860-4f9a-a851-1248a4884334">

**To Reproduce**
Go to Home Assistant MQTT Thermostat card and change the target temp

**Expected behavior**
Possibility to change the target temp in 0.5 celsius steps over home assistant 
**Additional context**

**Comment by revk** [comment]
If you think I have an incorrect HA config, can you advise the change you need you need made to the JSON/MQTT messages sent. I am not an expert in HA.

**Comment by geni0602** [comment]
I think the MQTT messages are ok. 

In general, if you create a MQTT thermostat in home assistant, you can define the temp_step (default: 1)
https://www.home-assistant.io/integrations/climate.mqtt/#temp_step

I don´t know where to find the parameters for the automatic created home assistant MQTT thermostat in your code.

**Comment by revk** [comment]
We send MQTT for the config, there would be something to tell it 0.5C units.

**Comment by geni0602** [comment]
The temp_step: 0.5C  should be configured in the automatic home assistant discoverythat you have, if not in, the default is 1C
Unfortunately I can not make a proposal for the change, because I am not good at coding. 

Thanks a lot.

**Comment by revk** [comment]
OK someone may know how to change it and make a suggestion.

**Comment by geni0602** [comment]
The "temp_step" should be added some where here. May it could be synchronized with the step in the webUI. 
https://github.com/revk/ESP32-Faikin/blob/b7eede1f6e6276dd4f1b0eeb67741baba2e4aa2c/ESP32/main/Faikin.c#L2306

**Comment by revk** [comment]
Will look in morning

**Comment by revk** [comment]
Can we confirm it is `temp_step` I need to add?

**Comment by geni0602** [comment]
According to the home assistant Matt climate thermostat documentation, yes

temp_step float (optional, default: 1)
Step size for temperature set point.

https://www.home-assistant.io/integrations/climate.mqtt/#temp_step

**Comment by revk** [comment]
OK issued a beta, does that work for you?

**Comment by geni0602** [comment]
I'll test. Can I make ota update? I'll activate the beta chennal

**Comment by geni0602** [comment]
Looks good. Thanks.
![Screenshot_2024-04-18-19-02-48-11_c3a231c25ed346e59462e84656a70e50](https://github.com/revk/ESP32-Faikin/assets/62853417/5870fd02-fe97-4026-a261-348e5e53ae15)
