### ISSUE TITLE
FXDQ32A3VEB  (FXDQ-A3) doesn't have X50A or S21 port (wiring diagram attached)

### ISSUE THREAD

**Issue by alexcf** [revk/ESP32-Faikin#305]
I've got a FXDQ32A3VEB (i think 4 actually!), which are connected to a Madoka (piece of shit*) controllers. Looks like they're using the Diii-Net method to connect them.

Looking at the board, I've got an X35A for power, but no X50A for comms. The notes say: X24A (wireless controller), X33A (adapter for wiring) and X38A (multi-tenant connector) - is X24A interchangeable with the S21? Pic attached.

\* why anyone in their right mind would think building a BLE based controller was a good idea needs a good talking to.
PS. RevK - great work :)
![IMG_1261](https://github.com/revk/ESP32-Faikin/assets/2235893/2e27efd8-aba8-4574-9252-f325a4531e06)

**Comment by geni0602** [comment]
Did you try to measure the voltage on the x24a? 
https://github.com/revk/ESP32-Faikin/wiki/Wiring#connector
Do you get 5v pin1 and 12-14v Pin 4 GND is pin 5?

**Comment by alexcf** [comment]
OK, so closer inspection on the board (also finding out that my multimeter is broken), I noticed there is an X50A but it's not listed on the wiring diagram. I'm still going to test the voltage on those pins though, but... After a bit more digging, it looks like the X24A is designed for the infrared remote control, so generally just a receiver :(

**Comment by alexcf** [comment]
Confirmed all working!

**Comment by alexcf** [comment]
I was wrong. I couldn't get this working. It seems like the X50A isn't wired in. :(

**Comment by yiannosi** [comment]
Did you find a solution? I think I am facing a similar problem..
