### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by hAMMERlized** [revk/ESP32-Faikin#310]
Hi man,

thanks for that great module. It's not an issue, more a stupid question i guess but is it possible to see any changes / changelogs that are made before upgrading to a new version? Thanks.

**Comment by njh** [comment]
>There are no formal release versions, they are all just dated and git version. This shows at the bottom of the settings web page.

There is some documentation on current and past changes here:
https://github.com/revk/ESP32-Faikin/wiki/Work-in-progress

**Comment by hAMMERlized** [comment]
Thanks. That's it 👍🏼
