### ISSUE TITLE
[BUG] Current case seems to have a float/detached part

### ISSUE THREAD

**Issue by reedy** [revk/ESP32-Faikin#334]
**Faikin hardware**
N/A

**Daikin hardware**
N/A

**Describe the bug**
Using https://github.com/revk/ESP32-Faikin/blob/48c1db8/PCB/Faikin/Faikin.stl / https://github.com/revk/ESP32-Faikin/blob/48c1db8/PCB/Faikin/Faikin.scad it seems there's floating plate that's not attached to anything

OpenSCAD:
![Screenshot 2024-05-17 at 14 49 53](https://github.com/revk/ESP32-Faikin/assets/67615/6afc0e45-b67f-44a5-91d9-7706220474a5)

BambuStudio:
![Screenshot 2024-05-17 at 14 52 32](https://github.com/revk/ESP32-Faikin/assets/67615/76056ddf-4743-4ff5-9a53-99180f16cfca)

PrusaSlicer:
![Screenshot 2024-05-17 at 14 53 24](https://github.com/revk/ESP32-Faikin/assets/67615/37c9d87b-f8b7-4eb0-a8bc-b340ca34803e)

![Screenshot 2024-05-17 at 14 57 17](https://github.com/revk/ESP32-Faikin/assets/67615/81839b6a-802d-4e7e-a176-b750f748672d)

**To Reproduce**
1. Import the STL into a slicer, or the scad into OpenSCAD.
2. Look at the generated object..

**Expected behavior**

The part not to have an apparent floating/not attached part.

I could print with supports, but that seems wasteful, as it's not attached (is it supposed to be?). If it's necessary, it could be printed directly on the bed. But either way, it's unclear where it goes/what it would be used for.

The other part has something similar, but it is attached at either side of the model.

**Additional context**
n/a

Thanks!

**Comment by reedy** [comment]
It seems to be a regression from 48c1db8e6531d6a6cf116dbf3815d301777cbac3

If I use the file from before that, https://github.com/revk/ESP32-Faikin/blob/aa194f032697c8fcc73cf78b59b8a794f2c04b7c/PCB/Faikin/Faikin.scad or https://github.com/revk/ESP32-Faikin/blob/aa194f032697c8fcc73cf78b59b8a794f2c04b7c/PCB/Faikin/Faikin.stl it seems to be attached as one would expect:

![Screenshot 2024-05-17 at 15 01 45](https://github.com/revk/ESP32-Faikin/assets/67615/df7f61c3-9d42-4380-b602-18cf15927aff)

![Screenshot 2024-05-17 at 15 02 06](https://github.com/revk/ESP32-Faikin/assets/67615/025b0c3b-6aca-49ed-a074-d5b3ceef709c)

**Comment by revk** [comment]
I think it is an anomaly, infinitely thin, and my slicer does not even see it, just delete if yours does.

It is automatically generated so the "bug" would be in the PCB case tools, not here.

**Comment by reedy** [comment]
Fair enough.

If we split it into parts, we get something like this, which is trivially removeable from the print.

![Screenshot 2024-05-17 at 15 05 59](https://github.com/revk/ESP32-Faikin/assets/67615/7a5fbf58-9a99-4096-863c-7601d689d09f)

![Screenshot 2024-05-17 at 15 05 49](https://github.com/revk/ESP32-Faikin/assets/67615/b894cb65-6b7e-4d44-804d-733aa66ed1db)
