### ISSUE TITLE
Ota updates don't work when fixed ip is enabled

### ISSUE THREAD

**Issue by Utopia69** [revk/ESP32-Faikin#335]
Hi,
I'm running 5x Faikin-S3-MINI-N4-R2. 729c466 2024-05-14T08:53:28 S21 
When I insert a fixed ip ota updates check fails.
{"url":"http://ota.revk.uk/Faikin-S3-MINI-N4-R2.bin?XXXXXXX","fail":-3}

![image](https://github.com/revk/ESP32-Faikin/assets/45993289/52d72903-72a8-41cd-9a69-162de866f916)

With dhcp there is no problem.
I also tested to change 1 dns server to an ipv6 dns, this gives no solution.

Grtz,

**Comment by revk** [comment]
Interesting, I wonder if there is an issue with DNS being set, I'll have to look.

**Comment by Utopia69** [comment]
> Interesting, I wonder if there is an issue with DNS being set, I'll have to look.

Without dns servers problem is also there (but this can be normal without dns  servers)

**Comment by revk** [comment]
Yes, looks like DNS issue. I have done a beta release, please test.

**Comment by Utopia69** [comment]
Yup, beta is working
Thx
