### ISSUE TITLE
[BUG] - HA Climate entity loses target set temp

### ISSUE THREAD

**Issue by Nick-Sills** [revk/ESP32-Faikin#347]
**Faikin hardware**
Amazon purchased, 04/24.
aikin-S3-MINI-N4-R2: 729c466 2024-05-14T08:53:28

**Daikin hardware**
Daikin FTXM42R
Daikin FTXM20R

Connect to Faikin using EKRS21 Wiring Harness + Dupont cables

**Describe the bug**
Climate entities in Home Assistant occasionally lose the target set point and display nothing.

At first I thought this was an MQTT retention issue, but this happens for both MQTT and the Home Assistant native Daikin integration:

**Example using MQTT:**
<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/01822e86-773e-4862-84d2-1ff699993a89" width="300">

**Example using the Home Assistant native Daikin integration**
<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/eba60cdf-3f6e-433e-8cec-1bea0a2cd9b4" width="300">

**To Reproduce**
I just have to leave the set point unchanged for a day or so.  

**Expected behaviour**
Retain the last set temp

<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/da8ed184-89ab-4258-bebb-0285f37e38a1" width="300">

Thanks for reading!

**Comment by revk** [comment]
Can you dump MQTT messages for this?

**Comment by Nick-Sills** [comment]
It's difficult, because it can't be reproduced on demand, and both climate entities are now OK.

It's also happening without MQTT using the native Daikin integration, so I was thinking that MQTT messages won't help.

I'll see if I can reporoduce on demand somehow and dump the messages.

**Comment by Nick-Sills** [comment]
Good question. I'll check this when it happens and report back

**Comment by Nick-Sills** [comment]
It's happened again, and the web interface shows an empty target temperature:

<img width="371" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/162114112/001515e9-d101-4908-a27f-a27f56f732a5">

**Comment by Nick-Sills** [comment]
I think I've now worked out what's happening.  I can reliably make the target temp null by rebooting either Faikin board. I've been making multiple changes and causing reboots lately,  and didn't correlate the two until I specifically looked for it. Apologies for the long winded discovery here. 

So, after a reboot I have to go into the Web UI and move the set temperature slider to enable the Climate entity in HA to operate.

**Comment by revk** [comment]
Ok that is, none the less, somewhat odd, but makes slightly more sense.

**Comment by revk** [comment]
I need debug go the S21 messages really, to see why we are not getting temperature until is changed.

**Comment by Nick-Sills** [comment]
I just reboot both units after updating to the latest firmware, and guess what, the target temps were fine!  It doesn't seem to be as easy to reproduce as I thought. 

You might as well leave this issue closed, and if I ever notice this problem or a pattern to reproduce, I'll try and dump the messages.

**Comment by revk** [comment]
Thanks.
