### ISSUE TITLE
How do I reset the Faikin?

### ISSUE THREAD

**Issue by erikderzweite** [revk/ESP32-Faikin#352]
Hello,

sorry for the stupid question, but I did not find the answer in the documentation or in the issues:

How do I reset the Faikin? I seem to have mistyped the settings password and cannot change the settings now.

**Comment by revk** [comment]
Do you have MQTT configured?

**Comment by erikderzweite** [comment]
Yes, mqtt works.

Am 7. Juni 2024 19:06:08 MESZ schrieb RevK ***@***.***>:

**Comment by revk** [comment]
There is a factory reset command you can send via MQTT

<img width="1062" alt="Screenshot 2024-06-08 at 09 16 54" src="https://github.com/revk/ESP32-Faikin/assets/996983/802c4cc0-cf18-4b6a-8568-5d39563eab2d">
