### ISSUE TITLE
Only the subscribed state/hostname-topic gets a message from MQTT-Broker

### ISSUE THREAD

**Issue by climaJoe** [revk/ESP32-Faikin#355]
Hi, i just connected my new Faikin-board with two (for free) MQTT-Brokers and have always the same problem with it, that the only message which arrives in the MQTT.fx-programm is by subscribing the state/hostname-topic. No other subscribed topic (info/hostname, event/hostname..) triggers a message. 

What could be wrong here?

Thx, a Faikin-newbie (and MQTT-newbie too).

**Comment by revk** [comment]
The Faikin code does not issue any `event` messages, and the `info` messages are all (I think) debug, so it will not issue any of them if debug not enabled.

What messages were you expecting, specifically?

**Comment by climaJoe** [comment]
Thx, debug was indeed not enabled (was off by default). 

But after i enabled debug there are still not any data shown.

Under which topic i have to look for any data? again the normal info/hostname-topic? i'm using MQTT.fx for this.

I have read on other i-sites that "under debug" users got data-lines with infos about temp,outside,liquid,comp, fanfreq and more. But where in MQTT.fx is "under debug" ?

**Comment by revk** [comment]
Well there are a load of debug messages, but what specifically are you expecting?

**Comment by climaJoe** [comment]
Primarily i wanted to get some specific information about my daikin-device. And that in the shortest possible way, using the http.get(...../aircon/get_control_info)-function. Most important for me here: the indoor- and the outdoor-temperatur, what also was actually possible. But also other data like the liquid-temperatur or the fan-rotationval are interesting for me, but unfortunately not available via http.get(.../aircon/get_control_info). Therefore i tried also the MQTT-Way now.

So if you would know a way to get these other data also via this short http.get(....//get_control_info)-method - that would be really great.

Otherwise i will also go on with MQTT. And therefore one more question please (because i cannot find this load of debug messages in this MQTT-prog): If faikin is sending these debug-messages, which topic-form are then used then? Is it something like "debug/info/hostname" or "info/debug/hostname" or what else, so i can look via this topic in the MQTT.fx-programm what was sent.

**Comment by revk** [comment]
Simplest is to look at all messages and see what it is sending. Ie subscribe to #

Then you will know what to subscribe to.

There are settings to change around the way the topic is structured. And the manual does cover a lot of it.

**Comment by climaJoe** [comment]
It wooooorks!

I subscribed state/hostname/# and got endless messages under state/hostname, state/hostname/ha and state/hostname/status 

for example under state/hostname/status messages like this:

{"protocol":"S21","online":true,"home":22.5,"heat":true,"fanrpm":860,"comp":36,"outside":26.0,"liquid":35.5,"anglev":53,"Wh":209300,"power":true,"mode":"H","temp":25.0,"demand":100,"fan":"A","swingh":false,"swingv":false,"econo":false,"powerful":false,"comfort":false,"streamer":false,"sensor":true,"quiet":false,"autor":0.0,"autot":0.0,"auto0":"00:00","auto1":"00:00","autop":false}

Some of these data above i would like to get it also via the short http.get-(wifi)way. Is that possible, at least for the "fanrpm"-data and the "liquid"-data (my last request in this issue)?

Thx for help.

**Comment by revk** [comment]
The legacy http url code is designed to mimic the standard old Daikin WiFi module only.

**Comment by climaJoe** [comment]
Maybe another question: 

In my last post above i showed the MQTT-message sent under the state/hostname/status-topic, with an item "fanrpm":860 inside.

Unfortunately homeassistant uses the topic state/hostname/ha instead of state/hostname/status. "Unfortunately" because the MQTT-message sent under state/hostname/ha has instead of "fanrpm":860 the item "fanfreq":14.3 !?!?!?! Because this value 14.3 must be wrong anyway or what else should it say us?

Is that probably wrong value a bug by Daikin? (Or Faikin)?

Is there any posibility to correct that, because i want to see in the homeassistant the value 860 and not this sadly 14.3 for max. fan-activity for example.

**Comment by revk** [comment]
The latest beta does not use the ...`/ha` status any more as it is tied in with the MQTT will to handle availability.

`fanrpm` was changed to `fanfreq` to work with HA better, and is in `Hz`. So `14.3` is probably fine (858 rpm).

Do try the latest beta anyway, but that is probably all correct.

**Comment by climaJoe** [comment]
I just installed the latest beta: Faikin-S3-MINI-N4-R2: 1154176 2024-06-20T08:54:35

But after this i still have the same results in HASS. It still shows this 14.3Hz-value. Also after i deinstalled und reinstalled the mqtt-broker in HASS.

**Comment by revk** [comment]
But 14.3Hz sounds the right value, surely?

**Comment by climaJoe** [comment]
Ok, my mistake. per minute vs. per second of course, but more comparable and more usual with these devices would be per minute values. That's why I was a little irritated. I would use Hz more for high frequency things.

**Comment by revk** [comment]
Sorry, the change was because, as far as I know, HASS does not understand `rpm` as a frequency unit, only `Hz`, hence I was asked to change it some time ago.

Only other approach would be a setting to change units, which is not impossible.

**Comment by climaJoe** [comment]
Probably that would be a rather good idea: One Button more in the "advanced Settings" for defining the fan-rotation-unit for MQTT-Messages. 

Finally, even you yourself have used the RPM unit for the Faikin device page (which you see only typing the device-ip).

And it just bites a little bit if I'm looking first on your device page see the "fanrpm"-value and for comparison switching than to the HASS-output and see a complete different other digit for the same thing.

**Comment by revk** [comment]
Fine, a setting, see next beta in a few minutes...

**Comment by climaJoe** [comment]
I just installed this next beta, but my faikin-device tells me now: "MQTT not Connection" ?

**Comment by revk** [comment]
That suggests MQTT is not connecting... It will keep trying.

**Comment by climaJoe** [comment]
After i restarted the Homeassistant-OS on the VirtualBox again faikin also became able again to connect the HASS-MQTT-Broker, 
and now IT WORKS !!!!!


GREAT !

**Comment by climaJoe** [comment]
And the same for "Comp" too?

Probably the absolut best would be to make four lines possible 

Comp ---->  Xy Hz
Comp ---->  Xy rpm
Fanfreq ---> Xy Hz 
Fanfreq ---> Xy rpm

and let the user decide what of them he wants to see. And if he really wants all four at the same time.
(with two of them enabled by default)

Thanks!

**Comment by revk** [comment]
Hmm, comp is not converted, so must be in Hz from the S21 as that... I mean I could maybe.

[no pleasing some people]

**Comment by climaJoe** [comment]
Why not a faikin de luxe. 

Daikin will look bad on the other hand, that's for sure.

**Comment by revk** [comment]
OK I'm doing a `hacomprpm` setting.

**Comment by revk** [comment]
We are already *de luxe* :-)

**Comment by climaJoe** [comment]
Now in any case!

Thx once more.
