### ISSUE TITLE
Unable to Flash Firmware on Faikin ESP32-S3-MINI-1

### ISSUE THREAD

**Issue by LowKey88** [revk/ESP32-Faikin#357]
Hi,

I have a Faikin ESP32-S3-MINI-1 and I’m having trouble connecting it to WiFi. I suspect it might be a firmware issue and need assistance with flashing the latest firmware.

The board lacks a boot/reset button, and my attempts to jump the GPIO0 pin to GND to enter boot mode haven’t worked. Could you please guide me on how to correctly set this ESP into boot mode and flash the firmware?

Your help would be greatly appreciated.

**Comment by revk** [comment]
The GPIO0 works, but easier to use the USB pins.

**Comment by LowKey88** [comment]
I'm getting this error

esptool.py -p /dev/tty.usbserial-83120 write_flash 0x0 Faikin-S3-MINI-N4-R2-bootloader.bin 0x8000 partition-table.bin 0xd000 ota_data_initial.bin 0x10000 Faikin-S3-MINI-N4-R2.bin
esptool.py v4.7.0
Serial port /dev/tty.usbserial-83120
Connecting......................................

A fatal error occurred: Failed to connect to Espressif device: Invalid head of packet (0x05): Possible serial noise or corruption.

**Comment by revk** [comment]
Not sure what to say, ESP32-S3 has USB and those pins are they connected directly, there is nothing that can go wrong, and they worked for me when flashing the board before shipping.

**Comment by LowKey88** [comment]
I wanted to update you that I was able to flash successfully, and everything is working now.

Thank you.
