### ISSUE TITLE
Disable Led blinking when connected to wifi

### ISSUE THREAD

**Issue by kroon040** [revk/ESP32-Faikin#36]
Hi,

Is it possible when the device is setup and has connection to the home wifi that the led blinking stops, preferred off. Now I see the led blinking even when it's builtin.

 It should be nice to have an option in the webinferface to choose what the do with the led.

**Comment by patrickli** [comment]
I noticed this too. The LED is very bright even it is installed under the aircon shell. I ended up hiding it inside the PCB box which is black.

A related question, @revk can you explain what does the LED color/blink mean? I know steady green is normal operations but I've seen it blink blue. An explanation maybe in README would be helpful. Thanks.

**Comment by revk** [comment]
Putting in the manual is a good idea. I have done that.

It is possible to disable totally with a setting, e.g. `setting/GuestAC {"blink":[0,0,0]}`

Having a mode for LED only when "something wrong" is an idea. I could do that if people want.

**Comment by patrickli** [comment]
@revk Thanks for putting things in the manual but what does green mean? mine blinks green when the aircon is off.

**Comment by revk** [comment]
Err, it should not do green! It might mean the LED does not have a "red", i.e. faulty board.

**Comment by patrickli** [comment]
hm... doesn't make sense right? It should do yellow when off and green is not part of yellow. Let me test it tomorrow with a few different operation modes.

**Comment by revk** [comment]
Err green is very much part of yellow! Yellow is green+red. So a faulty red would make the attempt at yellow show green.

**Comment by patrickli** [comment]
Yeah you are right. I'm being silly. Anyway I will do some test to prove it.

**Comment by revk** [comment]
Let me know if you want a replacement.

**Comment by patrickli** [comment]
Tested a bunch of modes and the LED doesn't blink anything that needs red. So you might be right. As for replacement etc, is there anyway we can discuss privately? I don't want to hijack OP's ticket.

**Comment by JeanOlivier** [comment]
> Putting in the manual is a good idea. I have done that.
> 
> It is possible to disable totally with a setting, e.g. `setting/GuestAC {"blink":[0,0,0]}`
> 
> Having a mode for LED only when "something wrong" is an idea. I could do that if people want.

That'd be nice. Better than always off IMO.

**Comment by revk** [comment]
Simplest is probably a DM on https://toot.me.uk/@revk

**Comment by revk** [comment]
OK a mode to have LED off for "normal working"... I'll look in to it.

**Comment by kroon040** [comment]
Agree that should be a nice option

**Comment by revk** [comment]
I think I'll expand the LED colours to better show state anyway - but a dark mode makes a lot of sense.

**Comment by revk** [comment]
I have updated the LEDs, added a `dark` settings, and also added a test mode - connecting tx and rx detects loopback and causes red/green/blue LED cycle, so as to allow simple testing of tx, rx, and all LEDs to avoid any issues with faults in future.

**Comment by revk** [comment]
You don't need to be on the same server to send me a message. I don't see a message from you yet. @revk@toot.me.Uk
