### ISSUE TITLE
hardware problem?

### ISSUE THREAD

**Issue by tane64** [revk/ESP32-Faikin#360]
**Faikin hardware**

Faikin-S3-MINI-N4-R2

**Daikin hardware**
S21

**Describe the bug**
I have 5 Daikins in my house all are now connected via Faikin.  One of the Faikins is saying that the "System is offline" Daikin is working fine with the built in WiFi.  When in switch the faikins with one of the others unit will work fine. The not working version will display the same message on the other Daikin. Looks like a problem with the faikin. Firmware upgrade did not solve the problem.  Also the beta firmware. Is this a hardware problem?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by revk** [comment]
Sounds like a hardware problem, did you get from Amazon, they should handle a return OK.
