### ISSUE TITLE
[BUG] - 'dict object' has no attribute

### ISSUE THREAD

**Issue by 1mfaasj** [revk/ESP32-Faikin#368]
**Faikin hardware**
Bought from Amazon.co.uk

**Daikin hardware**
- BRP069C4x
- connected the faikin device in the S21 port.

**Describe the bug**
my Home Assistant log reports these warnings, very often. Similar to https://github.com/revk/ESP32-Faikin/issues/365 but now for different attributes. It began actually when you asked me to switch to beta and I enabled Additional HA switches.
now I switched back to 'normal' but the warnings stays.

```
Template variable warning: 'dict object' has no attribute 'power' when rendering '{{value_json.power}}'
Template variable warning: 'dict object' has no attribute 'streamer' when rendering '{{value_json.streamer}}'
```

I already used powerful mode and stream/filter options in the faikin interface:
![image](https://github.com/revk/ESP32-Faikin/assets/71582854/6bc63a46-86ea-46d1-97d4-7b55e9840f0b)
but the warnings stays

when I execute
state/FaikinZolder1/ha
it gives me:
```
{
  "online": true,
  "target": 25,
  "temp": 24.5,
  "outside": 24,
  "liquid": 24.5,
  "comp": 0,
  "demand": 100,
  "Wh": 268700,
  "fanfreq": 0,
  "mode": "off",
  "fan": "auto",
  "swing": "off",
  "preset": "home"
}
```

**Comment by revk** [comment]
`power` is not `powerful`

But odd. Does it all go away if you turn it on?

**Comment by 1mfaasj** [comment]
No, I've tried every option

**Comment by revk** [comment]
- Ok what status is HA looking for?
- What does the status post have on MQTT?
- Are you on latest beta?

**Comment by 1mfaasj** [comment]
Hi the warning above disappeared when I clicked on some buttons, but after testing further with beta the mqtt device becomes unavailable in HA. Even after a reboot of the faikin device, HA or completely power off-on doesnt recover it.
After switching back to Normal release it is available again. I did this three times now (normal to beta and visa versa)
Any idea what is causing this?
It works when I use the Faikin interface by its IP address. Only not in HA.
No logs in HA about the unavailable state.

**Comment by 1mfaasj** [comment]
Looks similar https://github.com/revk/ESP32-Faikin/issues/369

**Comment by revk** [comment]
I don't understand how, but the current beta release was built with an old version of the library that broke availability.

**Comment by 1mfaasj** [comment]
ok let me know if I can test

**Comment by revk** [comment]
The beta is done, so yeh, test.

**Comment by 1mfaasj** [comment]
looks like the issue is resolved with the latest beta (both). thanks!
