### ISSUE TITLE
[BUG] Device not available in home assistant after Beta 2024-06

### ISSUE THREAD

**Issue by geni0602** [revk/ESP32-Faikin#369]
**Faikin hardware**
ESP32 own bild
**Daikin hardware**
Daikin Perferra s21 port
**Describe the bug**
After update from last Beta, the device is not available in Home Assistant. Mqtt is connected and WEB GUI is ok. Something with availability for home assistant is not correct. Update of stable version resolves the issue 
**To Reproduce**
update to last beta, after that the topic state/hostname/ha is not refreshing  

**Expected behavior**

**Additional context**

**Comment by andreas-bulling** [comment]
same here

**Comment by revk** [comment]
I will look again this morning.

A lot of testing was done on this, so I am rather surprised.

Hopefully a simple fix.

**Comment by geni0602** [comment]
Let me know, if you need an additional debug. Home assistant version is core 2024.6.0

**Comment by revk** [comment]
I don't understand how, but the current beta release was built with an old version of the library that broke availability. New beta in a few minutes. Apologies, very odd indeed.

**Comment by geni0602** [comment]
It's looking good. Just update from beta and everything is ok.

Thanks.
