### ISSUE TITLE
IPv6 Support with SLAAC

### ISSUE THREAD

**Issue by kroon040** [revk/ESP32-Faikin#38]
Hi,

Is it possible to add ipv6 support with SLAAC. I know it's already in the ESP-IDF frameworks. It should be nice to have. Also connecting then with ipv6 to the mqtt broker.

**Comment by revk** [comment]
I thought that was already turned on. I'll check.

**Comment by revk** [comment]
Apologies for that, for some reason it was not set on the config for the code issue build. I have enabled and issued new code.

**Comment by kroon040** [comment]
HI,

I see get get a Link local ipv6. I must check if I get an IPv6 global with SLAAC. 

2 questions:

-Ccan I put in the mqtt broker also my ipv6 global address and it should work? It should ben nice to have in te interface a status that mqtt is connected in  the settings.
- Is it possible to have the netwerk info also in the settings, so I see the ipv4 adress, dns and ipv6  link-local and ipv6 global.

**Comment by revk** [comment]
Not a bad idea, I'll look in to that.

**Comment by kroon040** [comment]
I check and filled in the mqtt broker ipv6, and that worked. And by that I see also de IPV6 Global address (mqtt broker is in another subnet). In the logging of the broker the ipv6 global address appeared

**Comment by revk** [comment]
Showing DNS is proving more complex, but showing IPv4/IPv6 is simple, so doing that in settings page.

**Comment by kroon040** [comment]
ok , thats enough. And than state of mqtt also in this page (connected/disconnected)

**Comment by revk** [comment]
Sorry, yes, it shows if MQTT is connected.

**Comment by kroon040** [comment]
Yes I see it works. Maybe in MQTT connected more loig to place it between MQTT Pass and set button, so you see in that section when connected

**Comment by kroon040** [comment]
I got today my second esp32 faikin, and when configuring I noticed whatever I fill in in the MQTT settings , it always say connected, while mqtt wasn't connected.

**Comment by revk** [comment]
Interesting - might be something of mistake then.

**Comment by revk** [comment]
OK it was a simple simplistic, saying connected even if the client was trying to connect. I have updated and made a tick next to the MQTT host field now.

**Comment by kroon040** [comment]
Tested on smartphone and laptop, I only get strange characters. Also in incognito browser

![Screenshot from 2023-06-04 14-19-54](https://github.com/revk/ESP32-Faikin/assets/40452265/c56645c2-8836-4e97-81a3-b3721304bfff)

**Comment by revk** [comment]
Odd, something is not realising the page is utf-8. I'll see if I can work out how you do that. Works on Safari, but maybe it assumes UTF-8.

**Comment by revk** [comment]
Yes, utf-8 was missing on the settings page. I'm surprised it is not default to be honest. Try now.

**Comment by kroon040** [comment]
Now it works as expected
