### ISSUE TITLE
[BUG] MQTT Topic for "setting"

### ISSUE THREAD

**Issue by lorbetzki** [revk/ESP32-Faikin#400]
Hello,

i'm not really sure if this is a bug, but in your advanced.md i found this section
![image](https://github.com/user-attachments/assets/2423ed1c-b1c7-4859-a1e9-52102f2f83fe)

but i cannot send setting/hostname i need to send setting/ID. If i enable "prefixhost" in the advanced settings it turns to

ID/setting, but i expect hostname/setting like the image said on the "prefixhost"-line

![image](https://github.com/user-attachments/assets/986366ef-6bcd-4d7d-9309-593500fa897d)

And now to the initial question, is it a bug or is it intentional? 

Best regards

**Comment by revk** [comment]
The hostname should work. What did you set the hostname to?

I can retest here, but most of my stuff uses the hostname.

Bear in mind if prefixapp is set it is appname/hostname

**Comment by lorbetzki** [comment]
HI,

I apologize, I expressed myself in a misleading way.

I can send a json like {dark: true} to hostname/setting (in my case, ac-dach/setting), but if i send without payload, i received all the existing settings to id/topic

MQTT Explorer shows
![image](https://github.com/user-attachments/assets/55d90920-8ad2-4565-853e-821cf83ec306)

but i expected to receive the existing settings to hostname/setting

Best Regards

**Comment by revk** [comment]
Ah, I see. That may be a documentation omission. That is deliberate.

Unlike `command` and `info`/`status` messages which have a clear direction, the `setting` is used to set settings, but it did not fit well to make this setting dump response something different. As such the response is the same as the setting command. Not ideal design, I agree. But only matters when two devices have the same hostname, for example, as each will see the response as address to them to change settings.

I'\ll update documentation.
