### ISSUE TITLE
[BUG] Unit switching from cooling to heat after approx 40 mins on its own

### ISSUE THREAD

**Issue by urbozz** [revk/ESP32-Faikin#406]
Using the Faikin from Amazon, on a FVXG25K2V1B using S21, the unit is set to Cool using HomeAssistant (so via MQTT) after a period of time, the unit sets itself to heat. I have been able to replicate the issue consistently. Appears to have start happening after turning off the Faikin auto mode. Log from HomeAssistant showing the unit setting Heat. Let me know what diagnosis may be useful.

![Screenshot 2024-07-29 at 22 58 50](https://github.com/user-attachments/assets/9e08d4fa-393a-48ff-9de4-08bdd79bd20b)

**Comment by revk** [comment]
Can you screenshot the control page on the Faikin?

**Comment by urbozz** [comment]
While in Cool - just turned on, will take another once switched to heat.
![Screenshot 2024-07-30 at 09 09 12](https://github.com/user-attachments/assets/6a8a283b-6ebd-47c6-9c9e-62b8b8470644)

**Comment by revk** [comment]
Somewhat at a loss, there is some MQTT logging from the Faikin, which may help, if you can capture it.

With the Faikin auto off, and the timed/auto off, it should indeed not change by itself.

**Comment by urbozz** [comment]
I power cycled the whole system, and since then cannot replicate the issue, suggesting it may have been the Daikin itself setting itself to heat.
