### ISSUE TITLE
[BUG] cloudflared proxied faikin not working

### ISSUE THREAD

**Issue by jsapede** [revk/ESP32-Faikin#411]
**Faikin hardware**
 Faikin-S3-MINI-N4-R2:

**Daikin hardware**
S21

**Describe the bug**
im getting access to my homelab using cloudflared tunnelling but impossible to get access to faikin interface.
On local LAN works without problems, but after proxying it through cloudflared got following errors : "Header fields are too long"

**To Reproduce**
1. Launch cloudflare tunnel
2. add hostname
3. browse hostname

**Expected behavior**
nomal access to the page.

**Additional context**
all my homelab apps are proxied using cloudflare without any problem

**Comment by revk** [comment]
Sounds like something is adding (long) header fields?

**Comment by jsapede** [comment]
I dont really know, never had problem on any apps with those tunnels witch acts like a proxy over vpn

**Comment by revk** [comment]
Well it is a tiny microcontroller and allocates some static buffers in the http server handling. So the config needs to know how big.

It would help to know what headers and how big!

**Comment by jsapede** [comment]
> Well it is a tiny microcontroller and allocates some static buffers in the http server handling. So the config needs to know how big.
> 
> It would help to know what headers and how big!

Ixhave non Idea how to proceed but if you need some logs i Can have a try

**Comment by revk** [comment]
I don't know either, the http server is part of the ESP IDF, so not sure if I can get any logs, and if I could it would be over a serial debug port.

Do you have anything else you can access in the same way that allows you to dump/report what headers are sent?

Or can you packet dump on your LAN (this is http not https so should be clear).

**Comment by revk** [comment]
If you are able to find headers being sent, but setting something else to access by proxy, then that may allow me to address the issue. Re-open if/when you do.

**Comment by jsapede** [comment]
Ok now in winter in thebhouse with the hvac i made some extra tests 

Accession the main page through cloudflared tunnel look ok

![Screenshot_20241207-102357.png](https://github.com/user-attachments/assets/fb03be42-cbc8-4d9e-b14c-7bcf3bcfcbde)

When i go to the settings page got error 

![Screenshot_20241207-102412.png](https://github.com/user-attachments/assets/21857e0e-ce96-4b32-8bd3-da0f9fa88ced)

But, if i directly go to the settings page with its URL it works 

![Screenshot_20241207-102431.png](https://github.com/user-attachments/assets/b1a8b29b-91a5-4074-8b06-91613763e721)

In this page if click on the various pages links, it shows the same error 

Reverting back to the main page exhibit same behaviour. Clicking on the link AT page bottom rises error while using directly homepage URL works. Looks like some referers or ws could be source of the problem.

**Comment by revk** [comment]
Yeah, it is adding extra headings that are too long.

**Comment by jsapede** [comment]
Investigating further with développement console shows error is coming from ws requested over HTTPS
 
Reading ai explanations in the chrome console tells to modify settings to allow wss connection.

Moreover it only returns errors in chrome. Using Firefox poses no problems

**Comment by jsapede** [comment]
![image](https://github.com/user-attachments/assets/c05c91e7-8d40-4514-8c8c-f994371cdfb5)

**Comment by jsapede** [comment]
![image](https://github.com/user-attachments/assets/68be0690-cdb7-4e1f-883f-443830a25fa8)

**Comment by revk** [comment]
Given the the control/web page is not https it makes sense that we would use ws, not wss, for the web socket.

This really is a tad silly, you are wrapping it in https and expecting it to work.

**Comment by jsapede** [comment]
Well, the initial problem is that the climate control heating of a holyday house and used to heat it 1 or 2 days before we arrive

As house use over the year, connection IS made with low cost 4G mobile router. As most of 4G connections it uses CGNAT with no ability to redirect ports

The only way found to Access it was to use cloudflared tunnel, witch IS a sort of hosted proxy combined with vpn. Cant even try with a simple proxy as the connection doesnt have a "Real" IP.

With many others apps involving ws (homeassistant, immich, vscode ...) it usually works flawlessly having HTTPS connections on the cloudflared proxy.

**Comment by revk** [comment]
OK, the code does handle HTTPS already.

```
                  "ws=new WebSocket((location.protocol=='https:'?'wss:':'ws:')+'//'+window.location.host+'/status');"   //
```

So not sure why your browser is not doing that. `location.protocol` should be `"https:"` so it should use `wss:`

**Comment by jsapede** [comment]
Ok thx, will try to have a look with the security settings maybe 
Thx for the help
