### ISSUE TITLE
[FEATURE] Pullup resistor on RX line

### ISSUE THREAD

**Issue by dwmw2** [revk/ESP32-Faikin#418]
**Daikin hardware**
Mitsubishi Ecodan

**Is your feature request related to a problem? Please describe.**

The Mitsubishi units don't seem to have their own pullup on their TX line.

**Describe the solution you'd like**
Please add another 10kΩ resistor to pull up pin 2 of J1 to pin 1.

**Describe alternatives you've considered**
I used an external one. It is messy.

**Comment by revk** [comment]
A second pull up would pull Tx to Rx if no 5V line!

**Comment by dwmw2** [comment]
And a diode or two then?

**Comment by dwmw2** [comment]
Anything but this:
![PXL_20240809_171042336 MP~2](https://github.com/user-attachments/assets/19c0ea98-6c46-4eec-b1d5-1a4e6283a2cc)

**Comment by revk** [comment]
I mean maybe diodes. Pain in the arse when so many just work.

**Comment by dwmw2** [comment]
True, but it would be amazing if it worked out of the box for the Mitsubishi units too.

**Comment by revk** [comment]
A diode will introduce a drop which is a problem. I suspect it has to be a FET or something. I'll have to see if possible. But not ideal.

**Comment by revk** [comment]
One thing we could do, and you could test.

We pull up Tx, the issue is Rx, which presumably they are only open-drain driving, hence needing a pull up.

We could pull that up to 3.3V, can you try that?

The only issue is if they drive at 5V on some models. At 10k would mean 200uA driving to the 3.3V supply, which I doubt would be a problem. So we can probably safely add a 10k on the Rx side to our 3.3V rail, and that would keep it independent of the Tx and (optional) 5V rail.

**Comment by revk** [comment]
OK I can make a small batch with a pull up - but we need to test on this model and others. It will take a week to arrive.

**Comment by revk** [comment]
I'll need some addresses for sending some test boards. Email in to A&A FOA me (Adrian).

**Comment by dwmw2** [comment]
Sounds good, thanks!

**Comment by dwmw2** [comment]
Perhaps it ought to be robust enough even for 12V on the RX line, even if that happens by accident?

On the quad FTDI board which was also working with this heat pump, its unconnected RX line floats at 2.4V — about a 0.7V drop from 3.3V?

2.5V ought to be perfectly sufficient; it's enough for the Faikin board itself to be able to tell the difference between floating high, and something external pulling it down to ground.

How about a diode with the pullup so that nothing at all can feed in to the chip power rail?

**Comment by revk** [comment]
I'd be surprised at anything not 5 or 3.3.

**Comment by dwmw2** [comment]
I dunno. I just found a better 10kΩ resistor to put directly in the Dupont plug and tried plugging it in, and it didn't work (didn't power up at all) Probably got the five pins in the wrong order, and 12V ended up *somewhere* it shouldn't... (still works with old cable pictured above though, so no harm done).

**Comment by dwmw2** [comment]
The units with the built-in 10kΩ pullup work well on the Mitsubishi Ecodan heat pumps, thanks!

**Comment by revk** [comment]
Perfect. I should have some with a diode soon just to be neater.

**Comment by dwmw2** [comment]
Makes sense.

_"Never assume the user won't apply 12 volts to a pin which didn't expect it"_ is certainly a good maxim to live by.
