### ISSUE TITLE
[BUG] 8266 release publishing

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-Faikin#419]
Hello!  Recently you merged at least one 8266 release, however Faikin-8266.bin (and .desc) on your server are outdated:
Commit id: c8f49f5
Date: Jul 26 2024
These are from e012d4de9f8bd9404290b6b30cbc42c9e2209ece , but the recent update is 3ae4feb905386d5c8d90f7d6eb3b6ea2224c658f

**Comment by revk** [comment]
I just need to pull in to my server.

**Comment by revk** [comment]
pulled
