### ISSUE TITLE
[BUG] Forgot mqtt and login settings after auto ota update

### ISSUE THREAD

**Issue by bigmoby** [revk/ESP32-Faikin#428]
**Faikin hardware**
This is a Faikin purchased from Amazon. (Faikin-S3-MINI-N4-R2: b16bfc4 2024-08-12T14:02:04 S21)

**Describe the bug**
After a clean Faikin installation (through dupont wires...) and a plain first-access in order to define ssid, wifi password, all mqtt settings and password access, I could access to the settings pages and it was perfectly fine. After that the device automagically updates itself and once it rebooted I wasn't able to access Settings page: "wrong login password" and also the mqtt settings are wrong. Now, I think, I am forced to reset the device.

**To Reproduce**
1. First installation and successful Settings page access
2. Auto OTA update
3. Unable to access to Setting page because wrong login password and also mqtt settings are lost.

**Expected behavior**
After the automagic firmware update all setting should be maintained

**Additional context**
How I could reset the Faikin device?

**Comment by revk** [comment]
Do you have any screenshots? This does not seems to make a lot of sense.

At present the only way to factory reset is using a usb lead to pads on the back.

But I need to understand how it has got in to this state. Unless you explicitly filled in the password field in settings, it should not need a password!

**Comment by bigmoby** [comment]
Yes, sure, these are the screenshots...I don't know if useful, I don't think so.
As described in the issue, after the first boot I applied the wifi, mqtt and login settings. After that the device has been updated (autoupdate) and rebooted and missed all the settings but the wifi settings remains working.
Thank you for your help!


![Screenshot_20240813-201709.png](https://github.com/user-attachments/assets/7e48f7cf-8719-4a5f-bd7e-bee10e6b4e9f)

![Screenshot_20240813-201722.png](https://github.com/user-attachments/assets/e6bc5b15-9c4b-4f39-b881-3bf5590c87ca)

**Comment by revk** [comment]
Ok that only makes sense if you set a password.

I'll have to work out a factory reset, assuming you don't have a lead and tools to do yourself.

**Comment by bigmoby** [comment]
> Ok that only makes sense if you set a password.

Yes, I've applied the password (...and there's no mistake...I remember it 🙂) but now it is identified as wrong.

> I'll have to work out a factory reset, assuming you don't have a lead and tools to do yourself.

I have a USB to serial converter (like this 
https://amzn.eu/d/5VDxz50 ) that I use to "tasmotize" sonoff relay. Is it useful in order to reset or flash?

**Comment by revk** [comment]
You can either connect to 4 pins for USB or the 5 pins for serial and GPIO.

There are flash instructions somewhere in the documents, but you want to erase flash first to clear the stored settings including password.

**Comment by bigmoby** [comment]
Thank you @revk for your support. Please, could you give me some directions or photos of the contacts I will have to create between the converter and the faikin?

**Comment by revk** [comment]
Does this help?

![71HoJTxV2HL _SL1500_](https://github.com/user-attachments/assets/10591127-4cfe-4293-a29b-56408e83f4b8)

**Comment by revk** [comment]
I believe it usually gets connected to DTR on a serial lead for that purpose, but yes, if shorted to GND it will go in to boot mode on power up.

**Comment by bigmoby** [comment]
Hi @revk , I tried to reset but when the Faikin is reconnected to the AC nothing happen...neither the menu! Is it bricked?!

![Uploading Screenshot 2024-08-15 at 12.06.47.png…]()

**Comment by revk** [comment]
You erase flash, so it is bricked, yes, obviously.

Now reflash the code.

**Comment by bigmoby** [comment]
Ok perfect, should I clone the project and recompile by myself or could I download a builded firmware?
Thanks

**Comment by revk** [comment]
There are some instructions on loading the binaries from the project release directory, that is probably best.

If you build yourself, you would have your own signing key and it would not auto update in future.

But up to you.

**Comment by bigmoby** [comment]
Great! Thank you for you support @revk 🙌
I'll provide to create a PR in order to improve the README and add a section for reset and re-flash the device, if you want.

<img width="1452" alt="Screenshot 2024-08-15 at 12 41 16" src="https://github.com/user-attachments/assets/8070480e-7262-43bc-aaff-80bad12cd668">

**Comment by revk** [comment]
Thanks.

**Comment by bigmoby** [comment]
Hi @revk , I create this PR https://github.com/revk/ESP32-Faikin/pull/438 
Thanks again for your support 👍

**Comment by revk** [comment]
No problem, glad it is all sorted.
