### ISSUE TITLE
[Hardware] Faikin unable to boot

### ISSUE THREAD

**Issue by dandwhelan** [revk/ESP32-Faikin#429]
**Faikin hardware**

![faikinback](https://github.com/user-attachments/assets/1bbd9cff-9af9-45b5-907c-8b826aa869a5)
![Screenshot 2024-08-12 221122](https://github.com/user-attachments/assets/1f07146d-53f4-4733-9fed-7a5cfaa1bde5)

**Daikin hardware**
I've a Daikin Heatpump Altherma Monoblock EDLA06E2V3

**Describe the bug**
I've purchased two Faikin units from Amazon, One was a few months ago and the second was yesterday in hope there was an issue with the one I purchased a few months ago. I have tried both on my headpump using the below instructions and I cannot get the Faikin to startup, flash, light up or broadcast a WiFi AP.

I've followed two guides. One was a Youtuber with visual instructions and a second was a document I found on how to wire the device into my headpump.

https://raomin.github.io/ESPAltherma/
https://www.speaktothegeek.co.uk/2024/03/daikin-altherma-3-heat-pump-and-home-assistant/

**Expected behavior**
I expected to plug this in, lights to start flashing and a WiFi AP becomes available.

**Additional context**
I have this USB Device which I was hoping could emulate power going to the device so I can see it booting. I'm not sure if this can be helpful for troubleshooting. 
I am using Female to Female jumper cables which I use for other ESPhome projects. I dont have a special case as I didnt think I'd need one. 

![usbtotll](https://github.com/user-attachments/assets/71d4ab28-ffb9-4b4a-b1ac-a20eddf49462)

Any help would be appreciated! Thanks

**Comment by Sonic-Amiga** [comment]
From your first photo i see that power (12V) is not connected. That's the power pin, not "+5V"
What is connector on AC side ?

**Comment by dandwhelan** [comment]
![Screenshot_20240813_035054_Photos](https://github.com/user-attachments/assets/78506f3d-82f7-4bbd-99d4-6aec8acd9e93)

**Comment by revk** [comment]
Yeh, you seem to have connect all except the power and then said it won't power up.

**Comment by revk** [comment]
That also looks like X10A not S21, is it the same?

**Comment by dandwhelan** [comment]
I have to use X10a due to the being no s21
I can try it with all 5 pins connected, but none of the guides seem to use pin 4 with my heatpump

**Comment by dandwhelan** [comment]
OK ill give it a try with all the pins connected. I was going off the below picture, as I couldn't find much documentation around the x10a. 

![Screenshot_20240813_080329_Chrome](https://github.com/user-attachments/assets/238e7d89-28ee-47bb-82be-d73927cac5fb)

**Comment by revk** [comment]
Ok if X10A has nothing on pin 4, then run the pin 1 5V from it to pin 4 on the Daikin.

It is designed for S21. On a real S21 connector pin 1 is either NC, or 5V but too low current to run an ESP.

**Comment by revk** [comment]
OK you can make a lot less noisy. Do you know if the X10A is compatible with S21?

You can change settings, set `nox50a` and `noswaptx` and `noswapx` that should try just S21 protocol.

The logs should be cleaner then.

If still no joy then, turn it all off and back on, it may be the aircon is confused by the attempts at alternatives.

**Comment by dandwhelan** [comment]
Unfortunately more of the same 

13/08/2024 10:50:39(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:37(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:35(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:33(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:31(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:50:29(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:27(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:25(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:23(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:21(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:50:19(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:17(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:15(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:13(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:11(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:09(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:50:07(-1.99 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:50:05(-2.01 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:03(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:50:01(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:59(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:57(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:49:55(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:53(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:51(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:49(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:47(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:45(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:43(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:41(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:39(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:37(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:35(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:33(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:31(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:29(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:27(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:49:25(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:23(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:49:21(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:19(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:17(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:15(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:13(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:49:11(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:09(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:07(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:05(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:49:03(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:49:01(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:48:59(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:48:57(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:55(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:48:53(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:51(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:48:49(-2.01 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:47(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:45(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:43(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:41(-1.99 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:39(-2.01 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:48:37(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:35(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:48:33(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:48:31(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:29(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:27(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:25(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:48:23(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:21(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:19(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:17(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:48:15(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:13(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:11(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:09(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:07(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:05(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:03(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:48:01(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:47:59(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:57(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:55(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:53(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:51(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FC"}
13/08/2024 10:47:49(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:47(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:45(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:43(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:41(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:39(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:47:37(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FF"}
13/08/2024 10:47:35(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}
13/08/2024 10:47:33(-2 seconds) 
{"protocol":"S21","cmd":"F1","noack":true,"value":"FE"}

**Comment by revk** [comment]
That does suggest that maybe it is not S21...

Do you have any reference for X10A being the same. Seems odd it would be different, but at this point I'd be looking at an oscilloscope. May be worth starting a discussion thread as a lot of users are on here and someone may know.

**Comment by dandwhelan** [comment]
Ok thanks for your help :)

**Comment by revk** [comment]
It may also be worth connecting pin 1 to pin 1 and 4, not just pin 1, if possible.

**Comment by dandwhelan** [comment]
I tried that out but no joy

**Comment by revk** [comment]
Is it connected to MQTT at all? If so we can do a factory reset.

If not, I'll have to work out a change to allow a factory reset for you.

Suffice to say, latest code is not causing this for other people. So all very odd.

**Comment by revk** [comment]
Sorry replied to wrong ticket!

**Comment by revk** [comment]
Worth trying to find anyone else that has used X10A basically. See if they had success.

**Comment by Sonic-Amiga** [comment]
@revk The picture he posted says "Altherma", and some time ago you added some stubs for this protocol. Seems you've got the first user to test it.
The picture seems to be taken from https://raomin.github.io/ESPAltherma/ ; so you may check their implementation.
However, seems Altherma is crappy; it only allows for monitoring and very basic on-off control via external relay, simulating a thermostat. As far as i can conclude from their description.

**Comment by revk** [comment]
Indeed, do let me know what works and does not work, and we can maybe get some dumps of what it sends.

**Comment by dandwhelan** [comment]
OK, as the heatpump is outside and the panels are awkward too fit I only
want to be doing this once or twice a week.

Can you please how to get a dump just in case it didn't work.

**Comment by revk** [comment]
There is a `dump` setting. It writes stuff to MQTT.

Ideally you try different settings and so on, and report what he MQTT dump shows and what the settings are so we can see which bits do what and hence ensure we can report it all.

**Comment by dandwhelan** [comment]
Nice one. I'll take a look today.
I'll keep the faikin unit plugged in for more testing.
