### ISSUE TITLE
[BUG] Gpio to GND without rezistor?

### ISSUE THREAD

**Issue by iulianhlc** [revk/ESP32-Faikin#449]
Hello,

I was looking at the schematic and I see a lot of GPIO pins to GND without a resistor. Is that ok?

**Comment by revk** [comment]
Why would that be an issue? They start as either unconnected or input.

**Comment by iulianhlc** [comment]
reason: not all gpio pins have pull-up/pull-down resistors

**Comment by revk** [comment]
Sorry, not sure of the issue.

Leaving floating would be possibly bad if no pull up/down, but tied to GND would be fine.

Pins tied to GND should be fine unless pin starts as an output and outputs high. None of those do.

Tied to GND with internal pull up wastes some current, but the code actually checks all ports for that and ensures that if tied to GND it is set to a pull down instead.
