### ISSUE TITLE
How to open the web config page?

### ISSUE THREAD

**Issue by MarkoSchweizer** [revk/ESP32-Faikin#456]
I have a stupid question.

I installed the faikin controller and connected my android phone to the wifi of the controller, but I don't get how I can open the web config page.

Please help!

Greetz 
Marko

**Comment by Sonic-Amiga** [comment]
Faikin should come up as a wifi access point. Connect to it, and you should see an invitation to a login page. Just follow it.

**Comment by revk** [comment]
Quite, iPhone and Android should have a "splash screen" when connecting to WiFi, automatically.

If not, you need to go to the IP address of the Faikin. Check IP settings and look for "router" or "gateway" IP, and enter that in browser.
