### ISSUE TITLE
Faikin MQTT command/ACGuest/mode switches AC on

### ISSUE THREAD

**Issue by ettom1710** [revk/ESP32-Faikin#458]
First of all - thank you for this nice piece of hardware!

I am using the Faikin module with a DAIKIN Perfera as well as with an EMURA.
The control of the AC is done via MQTT - unfortunately my home automation system is resetting the Mode every time it restarts which causes the MQTT command/ACGuest/mode to be resent.
I don't know why, but unfortunately a Mode Change via MQTT is automatically switching on the AC.
This is not the case e.g. for the command/ACGuest/fan - where the command is also resent with every restart and the AC stays OFF.

Is it possible to prevent the AC from switching on due to a MQTT mode change via command/ACGuest/mode ?

Thank you for your help!

**Comment by revk** [comment]
I expect I need details of they exact MQTT messages being used, sorry.

**Comment by ettom1710** [comment]
The exact MQTT messages used are:
publish command/ACGuest/mode A
publish command/ACGuest/mode C
publish command/ACGuest/mode H
publish command/ACGuest/mode D
publish command/ACGuest/mode F

**Comment by revk** [comment]
Ok I think the `mode` is defined as "set a mode and power on" to be honest, with *off* being a mode, does that make sense?

Why set mode `H` (`hear`) if not wanting `heat` as opposed to `off`?

**Comment by ettom1710** [comment]
I am using Loxone as home automation - there you have a module called "AC control" with several outputs for "status" (1...On, 0...Off), Mode, Fan, etc.
each of the output is connected with a MQTT command.
Whenever the home automation is restarting, the mode and fan outputs send a "0" for a short time followed with the last setting. This triggers the AC to switch on, as the Mode is sent again.

Is it anyhow possible to define the mode as "set a mode" without power on?

**Comment by revk** [comment]
Well possibly, and there may even be one, leave with me to check the code.

**Comment by revk** [comment]
Try sending `command/ACGuest/control` with `{"mode":"A"}`

That should just set the mode and not power.

You can use with `{"power":true}` and other settings in the JSON as needed.

**Comment by ettom1710** [comment]
Thank you.
I will try this solution.

**Comment by ettom1710** [comment]
Perfect! I just tried your solution and it works!
Many thanks for your help!!!
