### ISSUE TITLE
[BUG] Cant connect to wifi

### ISSUE THREAD

**Issue by Zappelphilipp** [revk/ESP32-Faikin#459]
**Faikin hardware**
Amazon 07.2024

**Daikin hardware**
S21 Port on Stylish

**Describe the bug**
Device shows as AP, i can connect to the Portal/Web UI but after setting the WIfi and pressing save nothing happens.

**To Reproduce**
Connect to Faikin AP, setup Wifi, Faikin does not connect to wifi

**Expected behavior**
Faikin connects to wifi and gets DHCP adress

**Additional context**
I have 2 wifis with about 75 iot devices without any problems. I also tried an android hotspot but same result. I read about a bug were the Wifi PSK needs to be shorter then 32 characters which is not the case on my wifis. 

EDIT: i am monitoring my mikrotik router regarding DHCP leases and i never see any deivce getting an ip

**Comment by Zappelphilipp** [comment]
UPDATE: Ok, i really don't know why, but after the ~40 try it suddenly worked without changing anything. can be closed i guess :)

**Comment by revk** [comment]
There was a bug, and a new faikin may have the older code until connected to WiFi enough to upgrade, perhaps.
