### ISSUE TITLE
fwt03catnmv1 Compatibility

### ISSUE THREAD

**Issue by Vortecsz** [revk/ESP32-Faikin#47]
Hello i have an fwt03catnmv1 fan coil air conditioner, the ac support the original daikin module, anyone know if the module could work with my ac? Thank's for the help

**Comment by joshbenner** [comment]
If it is one of the wifi modules that speaks the S21 protocol (such as BRP073* or BRP069*), then Faikin will _probably_ work -- but we can't know for sure until someone tries it and confirms. What was the model of the original Daikin module you're referring to?
