### ISSUE TITLE
[BUG] Fan settings disappeared in HA

### ISSUE THREAD

**Issue by eupesco** [revk/ESP32-Faikin#479]
In latest beta,  I cannot control the fan settings anymore in Homeassistant. They disappeared from the thermostat card.

**Comment by eupesco** [comment]
Sure, here the fan could be set until the last beta. In Faikin websettings, it still can be set.

![Screenshot_20240912_183320_Home Assistant](https://github.com/user-attachments/assets/91eb930e-6094-41ae-a6be-31e4fe8fda33)

**Comment by revk** [comment]
Ok we may need more debug.

The latest change should not have broken that. So I need to look in to it.

**Comment by eupesco** [comment]
I am not sure what happened during the night, but today the fan settings are back.

**Comment by revk** [comment]
Phew, thanks

**Comment by eupesco** [comment]
Well, it happened again with one appliance of my 3 multi split system. Not sure why it happens. I did not use the AC the whole day.

**Comment by revk** [comment]
OK can you check the HA diagnostics for what we set in config?

**Comment by eupesco** [comment]
[mqtt-87db2356cad565b4ef527f4c5fd5ee4a-AntonAC-167888853ae335baec9da6319a3c7306.json](https://github.com/user-attachments/files/16997062/mqtt-87db2356cad565b4ef527f4c5fd5ee4a-AntonAC-167888853ae335baec9da6319a3c7306.json)

Is this the correct file?

**Comment by revk** [comment]
Hmm, I'll look again.

**Comment by revk** [comment]
Sorry, still busy - hoping to look soon.
(trying to open a pub)

**Comment by revk** [comment]
OK, works for me, is this what you are expecting to see?
<img width="421" alt="Screenshot 2024-09-17 at 08 31 57" src="https://github.com/user-attachments/assets/41219e04-a660-4034-9db8-6c8571a3d6c2">

Under MQTT/device, the ... menu.
<img width="357" alt="Screenshot 2024-09-17 at 08 33 21" src="https://github.com/user-attachments/assets/5e953f71-6421-4bd2-803e-2b874acdf28a">

You can find the NVAC entry for discover data, e.g.
<img width="602" alt="Screenshot 2024-09-17 at 08 34 10" src="https://github.com/user-attachments/assets/d00b8102-a530-4c06-9f15-f331e7a728f3">

What to you see for discover data there?

**Comment by eupesco** [comment]
Exact - I cannot set the fan mode for this specific unit.

Further I cannot find fan_mode_*** in the /config topic (nor in any other topic). In my multisplit, I have another identical indoor unit, where fan_mode_*** is normally displayed.

**Comment by revk** [comment]
OK that suggests no fan in S21, which makes no sense.

Can you turn on `debug` and capture the logs of the S21 messages?

**Comment by eupesco** [comment]
I see following messages: 
`  "G1": "04GA",
  "G2": "=;\u0000",
  "G3": "000\u0000",
  "G4": "0°0",
  "G5": "000",
  "G6": "0°00",
  "G7": "l0JC",
  "GA": "4A30",
  "GB": "0440",
  "GG": "0000",
  "GK": "q{51",
  "GM": "5D21",
  "GN": "0000",
  "GP": "E400",
  "GQ": "7500",
  "GS": "4000",
  "GT": "3000",
  "Sd": "000"'

**Comment by revk** [comment]
OK I have a clue, can you follow those messages until you see "SG" as last item, and post that?

**Comment by eupesco** [comment]
```
  "SN": "521+"
  "SG": "A"
```
OK?

**Comment by eupesco** [comment]
Just checked the latest beta - fan mode is back. Thanks.
