### ISSUE TITLE
[BUG] Issue OTA update with Beta switch on

### ISSUE THREAD

**Issue by urbozz** [revk/ESP32-Faikin#485]
**Faikin hardware**
Amazon purchased, '1st gen'

**Daikin hardware**
S21 FDXS50CVMB

**Describe the bug**
Cannot update latest beta. Error - Upgrade check failed

**To Reproduce**
1. Set beta switch on
2. Click 'Upgrade now from ota.revk.uk (beta)'
3. Get error 'Upgrade check failed'

**Expected behavior**
Upgrade to latest Beta

**Additional context**
Footer info: Daikin-S1-PICO: b16bfc4 2024-08-12T14:01:38 S21

<img width="1338" alt="Screenshot 2024-09-18 at 10 14 20" src="https://github.com/user-attachments/assets/824c6e89-c241-4ccd-94a4-cca9e9cb7c0b">

**Comment by revk** [comment]
Very old if app name is Daikin! Try now.

**Comment by urbozz** [comment]
Works, thanks!
