### ISSUE TITLE
[BUG] env is not reported properly in MQTT Faikin/ topic if BLE is active

### ISSUE THREAD

**Issue by miniluma** [revk/ESP32-Faikin#488]
running the latest beta from 17.09.2024

**Describe the bug**
`livestatus` active
`fixstatus` inactive
`reporting` = 300
`nofaikinauto` active

1) (as expected)
Faikins with environment monitoring data received via MQTT command report `env`, and the env array in `Faikin/ `
Info: I send the measured-temp from a Homematic room sensor with 
`command/$DEVICETOPIC/control {"env":"$EVTPART1"}` 
(with `$DEVICETOPIC` as the faikin name and `$EVENTPART1` as temperature value).

2) (unexpected)
Faikins with BLE send env in `status/` but `Faikin/` only receives the array. The current value is missing.
The ble_.* as part of the status is sent as expected and equals the env value.

**Comment by revk** [comment]
Hmm, the `"temp"` report in status is the `env` we are using if set, else `home` if set, else `home` if set.

The `env` is set from BLE if available, or `command` with `"env"`, if being sent, so either of these will report the `"temp"` in status.

Separately, the status also includes `"bletemp"`, `"blehum"`, and `"blebat"` if available (though maybe they would be better in a `"ble`" object. Hmmm.

The `Faikin` message reports periodic statistics (array of min/ave/max, or single value, depending on setting) that are collected from the Daikin. But this includes `env` (set by BLE or `command`). It does not include the ble data separately.

So I think working as I designed...

**Comment by miniluma** [comment]
ok, when I disable `livestatus`, I see it as part of `Faikin` as well.

With `livestatus=1`, I see the env array (min/avg/max) in Faikin, but `Faikin/env` is not included. (`status/env` is updated as expected)

**Comment by revk** [comment]
OK that makes no sense.. I'll have to have another look.

But it was never in `Faikin` as it is not a *real* field from the aircon, the real fields are things like `home`, etc.

**Comment by revk** [comment]
Depends which reporting, you can find `env =` in a few places, setting from temp from aircon, or BLE, or the `control` messages.

**Comment by revk** [comment]
Sounds like the test is wrong there!

**Comment by revk** [comment]
That means `fixstatus` was wrong all along, I am fixing now - beta in a moment.

**Comment by miniluma** [comment]
tested with fixstatus == 1: Works perfect! Thank you. 

untested for fixstatus == 0.
