### ISSUE TITLE
System down - No connection to AC after initial setup

### ISSUE THREAD

**Issue by mikekuzak** [revk/ESP32-Faikin#499]
**Faikin hardware**
Amazon
Faikin-S3-MINI-N4-R2: b16bfc4 2024-08-12T14:02:04

**Daikin hardware**
 FTXS35BVMB - connected via S21

**Describe the bug**

After buying the adapter, I connected it 1-1 to the S21. I have power so I guess it's the right way around.
Entered the access point and connected to wifi and mqtt server.

The adapter is blinking blueish and I see these messages on the mqtt broker. 
```
2024-09-23T22:19:15: Received PINGREQ from Faikin:faikin-living-room_DB9418
2024-09-23T22:19:15: Sending PINGRESP to Faikin:faikin-living-room_DB9418
2024-09-23T22:19:17: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (33 bytes))
2024-09-23T22:19:19: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (37 bytes))
2024-09-23T22:19:21: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (37 bytes))
2024-09-23T22:19:23: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (41 bytes))
2024-09-23T22:19:24: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (34 bytes))
2024-09-23T22:19:27: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (38 bytes))
2024-09-23T22:19:29: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (38 bytes))
2024-09-23T22:19:31: Received PUBLISH from Faikin:faikin-living-room_DB9418 (d0, q0, r0, m0, 'error/faikin-living-room/comms', ... (42 bytes))

```

![image](https://github.com/user-attachments/assets/ca0fa06a-6930-4948-b478-73dfd5ad211c)

**Comment by revk** [comment]
If you have the payload of the mqtt messages, that would help.

And check connections carefully.

**Comment by revk** [comment]
OK that is trying different protocols, which suggests it is not seeing any replies.

If you lock it down in the settings, so setting `nox50a`, `noswaptx`, `noswaprx` should ensure it only tries S21 with no inverted signals. See if that helps.

Otherwise, as I say, possible wire/connection issue.

Failing that, possible faulty board.

**Comment by mikekuzak** [comment]
I have isolated to only S21. Same issue. I checked the wires with a multimeter for continuity. Here the picture of the board. I had it connected 1-1 with GND first pin from the bottom to Red wire on Faikin. 

![IMG_20241006_180134](https://github.com/user-attachments/assets/9dcfeddb-ecd1-484c-9d8a-8e6bd9b832ae)
![IMG_20241006_180057](https://github.com/user-attachments/assets/d4eb01f4-beaf-4679-8a49-03c043a5474c)

**Comment by revk** [comment]
Pin 1 has the triangle on the S21 connector, and is at the top and is the blue on the Faikin board and is not GND. Pin 5 is GND.

**Comment by revk** [comment]
Are you able to measure the voltage red to orange?

**Comment by revk** [comment]
Can you show the payload of the MQTT messages?

**Comment by mikekuzak** [comment]
> Are you able to measure the voltage red to orange?
around  -14.15V when setting the Multimeter to 20V

Sorry for the late response.

**Comment by mikekuzak** [comment]
> Can you show the payload of the MQTT messages?

Message 159 received on error/faikin-living-room/comms at 3:12 PM:
{
    "protocol": "S21",
    "timeout": true
}
QoS: 0 - Retain: false

**Comment by revk** [comment]
Sounds like not working at all, which is concerning. Not sure if anyone else had any suggestions.

**Comment by mikekuzak** [comment]
If I enable all protocols ... 

```
Message 1081 received on error/faikin-living-room/comms at 3:47 PM:
{
    "protocol": "Altherma_S",
    "payload": "",
    "bad-cs": "FF",
    "bad-cmd": "U"
}
QoS: 0 - Retain: false
Message 1080 received on info/faikin-living-room/tx at 3:47 PM:
{
    "protocol": "Altherma_S",
    "cmd": "U",
    "dump": "0255A8"
}
QoS: 0 - Retain: false
Message 1079 received on error/faikin-living-room/comms at 3:47 PM:
{
    "protocol": "Altherma_S",
    "payload": "",
    "bad-cs": "FF",
    "bad-cmd": "S"
}
QoS: 0 - Retain: false
Message 1078 received on info/faikin-living-room/tx at 3:47 PM:
{
    "protocol": "Altherma_S",
    "cmd": "S",
    "dump": "0253AA"
}
QoS: 0 - Retain: false
Message 1077 received on error/faikin-living-room/comms at 3:47 PM:
{
    "protocol": "Altherma_S",
    "payload": "",
    "bad-cs": "FF",
    "bad-cmd": "P"
}
QoS: 0 - Retain: false
Message 1076 received on info/faikin-living-room/tx at 3:47 PM:
{
    "protocol": "Altherma_S",
    "cmd": "P",
    "dump": "0250AD"
}
QoS: 0 - Retain: false
Message 1075 received on error/faikin-living-room/comms at 3:47 PM:
{
    "protocol": "Altherma_S",
    "payload": "",
    "bad-cs": "FF",
    "bad-cmd": "T"
}
```

**Comment by revk** [comment]
You do not want Atherma, just S21, but either tx or rx not working at all by the look of t.

**Comment by mikekuzak** [comment]
I have a second unit .. opened it up, used new cables .. same thing .. :( might need to return the unit 

```
Message 100 received on error/faikin-living-room/comms at 7:38 PM:
{
    "protocol": "S21¬Rx",
    "timeout": true
}
QoS: 0 - Retain: false
Message 99 received on info/faikin-living-room/tx at 7:38 PM:
{
    "protocol": "S21¬Rx",
    "dump": "0246317703",
    "F1": ""
}
QoS: 0 - Retain: false
Message 98 received on state/faikin-living-room/status at 7:38 PM:
{
    "protocol": "S21",
    "online": false,
    "autob": "582D3413D3E2",
    "autor": 0,
    "autot": 0,
    "auto0": "00:00",
    "auto1": "00:00",
    "autop": false
}
QoS: 0 - Retain: true
Message 97 received on state/faikin-living-room at 7:38 PM:
{
    "ts": "2024-10-19T18:37:48Z",
    "id": "24587CDB9418",
    "up": true,
    "uptime": 316,
    "mqtt-up": 312,
    "mem": 69824,
    "spi": 2069116,
    "online": false,
    "target": null,
    "temp": 18.95,
    "bletemp": 18.95,
    "blehum": 67.44,
    "blebat": 86
}
QoS: 0 - Retain: true
```

**Comment by revk** [comment]
Looks like not working at all still, no Rx.

**Comment by mikekuzak** [comment]
Returned. Sorry :(
