### ISSUE TITLE
[FEATURE] MQTT reboot command

### ISSUE THREAD

**Issue by ayasystems** [revk/ESP32-Faikin#503]
**Daikin hardware**
Faikin-S3-MINI-N4-R2: 1fa8ae5 2024-09-24T15:32:17 S21

**Is your feature request related to a problem? Please describe.**
Some times webserver is not responding but mqtt works fine so coul be a good point allow to send a reboot command

PING is responding 
mqtt is working
http connection raise timeout

![image](https://github.com/user-attachments/assets/9625e835-e2df-41ea-97ea-5c3e691dfea7)

**Comment by revk** [comment]
`command/Name/restart`

As per https://github.com/revk/ESP32-RevK/blob/master/revk-user.md

**Comment by ayasystems** [comment]
Thanks again, sorry, i didn't find it!
