### ISSUE TITLE
[FEATURE] Allow to change header device name

### ISSUE THREAD

**Issue by ayasystems** [revk/ESP32-Faikin#504]
**Daikin hardware**
Faikin-S3-MINI-N4-R2: 3e782e1

 

**Describe the solution you'd like**
I have bought another faikin. 
Could it be allowed to change the header name to identify which one we are using?

![image](https://github.com/user-attachments/assets/8f867dc9-770a-401f-80f6-e4e7427774c5)

**Comment by revk** [comment]
<img width="733" alt="Screenshot 2024-09-26 at 09 51 03" src="https://github.com/user-attachments/assets/a960ae6b-6861-461d-8d53-15ce156e181f">

**Comment by ayasystems** [comment]
OMG!! Thanks!!!
