### ISSUE TITLE
Need help for connection

### ISSUE THREAD

**Issue by Idaho947** [revk/ESP32-Faikin#515]
Hello,

I need some help to connecte my faikin on my new daikin perfera. I open the split and dont know where I can link the cable.

![PXL_20241004_093843670](https://github.com/user-attachments/assets/429b0e1c-e5cc-43d4-9180-352b7e4609ab)

Someone can help me ?

**Comment by revk** [comment]
The port on the left labelled S21.

**Comment by Idaho947** [comment]
Thanks for you very quick reply. I bought a s21 cable but it is to long : 
![17280396049858635305421601597309](https://github.com/user-attachments/assets/d638ae98-0c1e-4ec2-9bf0-568c8b0da304)

![Uploading 17280396425804086781754486172131.jpg…]()

**Comment by revk** [comment]
The port on the image you posted definitely has 5 pins.

![373612076-429b0e1c-e5cc-43d4-9180-352b7e4609ab](https://github.com/user-attachments/assets/33aa426c-20d9-4b75-b267-6edf92fc1d27)

**Comment by Idaho947** [comment]
Arf need new glasses... And my cable is good too ? Do you have some good link to buy some good cable ?

**Comment by revk** [comment]
I know a lot of people just use jumper wire. But I don't have any links, someone else may.

**Comment by Idaho947** [comment]
Thanks very much for your reply. Look at the jumper.

**Comment by Idaho947** [comment]
Hello those one are nice :
https://fr.aliexpress.com/item/1005006291181398.html?spm=a2g0o.order_list.order_list_main.5.21ef5e5bQxs1az&gatewayAdapt=glo2fra

**Comment by Idaho947** [comment]
Found good s21 wire
