### ISSUE TITLE
[BUG] FTXC35DV1B can read data but cannot send

### ISSUE THREAD

**Issue by aizerin** [revk/ESP32-Faikin#516]
**Faikin hardware**
My own HW. I cannot easily buy Faikin in my country.
ESP32-WROOM-32D
Faikin S1 build

![IMG_3545](https://github.com/user-attachments/assets/f4cf2cd5-e9d3-4384-ac75-861dc2cf75e8)
![IMG_3546](https://github.com/user-attachments/assets/886276b8-334d-4902-bffc-2bb93f2eab05)
![IMG_3547](https://github.com/user-attachments/assets/e40cb6d2-54c7-4731-9a4e-ce8586cf1869)

**Daikin hardware**
FTXC35DV1B
CN_S21

**Describe the bug**
I can see all the data from the uni in web UI, but I cannot control the unit.

I turned on debug I'm getting this message.
```
{"protocol":"S21","mismatch":true,"data":"024700000000004703"}
```
from info cannot-tx
```
{"protocol":"S21","cmd":"D1","payload":"31344635","text":"14F5"}
```

**Additional context**

I tried another board and double-checked the wires. 

What's strange is that when I use GPIO TX:1 and RX:3 as it should be I get system offline. If I swap these for TX:3 and RX:1 then Im able to read the data from the unit.

**Comment by revk** [comment]
Tx and Rx are always in the eye of the beholder, so not surprise. Mismatch is an odd error.

You can lock down to not try other protocols like no.x50a, etc, and tell it not to invert tx and rx (which is also tries) if you are sure of polarity.

**Comment by aizerin** [comment]
I tried that settings and result it same

**Comment by revk** [comment]
And nothing else connected as well? mismatch is a very odd message.

**Comment by aizerin** [comment]
What do you mean by nothing else? I have only AC unit, remote controller and faikin. I have a JST plug in S21 so the wires should be secured.

I also tried to use uart2 and the situation was the same.

**Comment by aizerin** [comment]
What should I send? I turned on dump and debug.

there are a lot of records in tx and rx.

TX
```
{"protocol":"S21","dump":"0246418703","FA":""}
{"protocol":"S21","dump":"0246317703","F1":""}
{"protocol":"S21","dump":"0246367C03","F6":""}
...
```

RX
```
{"protocol":"S21","dump":"024733303030303A03","G3":"0000"}
{"protocol":"S21","dump":"024700000000004703","G":"\u0000\u0000\u0000\u0000"}
{"protocol":"S21","dump":"024732343A8080E703","G2":"4:\u0080\u0080"}
...
```

**Comment by revk** [comment]
Rx looks messy, you sure you have the levels right? Daikin wants 5V typically.

**Comment by aizerin** [comment]
It should be fine. I have a level shifter - I tried two different boards to be sure that there was no failure.

**Comment by aizerin** [comment]
I have tested a few devices

esp-wroom-e32 - system offline
esp8266 - system offline
esp-wroom-e32d - only read

I will order level shifter from a different brand and esp32 s3.

**Comment by Sonic-Amiga** [comment]
Hello!
So, you are not getting data from the AC to controller, correct ?
Remember that these transistor-based converters require +5V pull-up; and you may not have it from the A/C
Here's a tested solution: https://github.com/Sonic-Amiga/ESP8266-Faikin/tree/main/Hardware/S21Adapter . I am actually using this on one of my two units, works like a charm despite utter simplicity. Tx (from Faikin) is inverted, Rx is not.

Yes, that's a 8266 repo and indeed i am using this contraption with a ESP32 board.

**Comment by aizerin** [comment]
The problem was with the level shifters I had. 

I bought a new SparkFun BOB-12009 and it works fine so far.
