### ISSUE TITLE
[BUG] System is offline.

### ISSUE THREAD

**Issue by TechnicGuy1** [revk/ESP32-Faikin#537]
**Faikin hardware**
from Amazon

**Daikin hardware**
S21 ATXC50

**Describe the bug**
Faikin Webgui say system is offline

Hello,

after i thought some wifi problems, restart Access Point, and again no webgui from Faikin. Set power off of the Daikin ATXC50. After some shutdown's, webgui is here. But "System is offline.", all cable are unchanged.
Any hints to get it "connected/online state" ?

Thanks, Best Regards Michael

**Comment by revk** [comment]
Not sure what to suggest - turn on debug and check MQTT maybe?

**Comment by TechnicGuy1** [comment]
After several reboots, faikin show normal, but no interaction on demand or temperature changes. Shutdown, and reconnectet all cable, and its running. Thanks ;)
