### ISSUE TITLE
[BUG] Some sensors are missing since <ebf3c2b> in HA (missing discovery topics)

### ISSUE THREAD

**Issue by con0aks** [revk/ESP32-Faikin#542]
**Faikin hardware**
Faikin-S3-MINI-N4-R2

**Daikin hardware**
FTXM35R (S21)

**Describe the bug**
I have three faikin boards running. I recently updated one of the boards.
Since the version <ebf3c2b 2024-09-26T14:35:29> some sensors are missing in HA (liquid temp, comp freq, fan freq).

**To Reproduce**
-

**Expected behavior**
On the other boards I got five sensors (liquid temp, comp freq, fan freq, outside temp, lifetime energy) in HA.

**Additional context**
The sensor values are present in the mqtt-topics, but the configs for discovery are missing.

**Comment by TheBestMoshe** [comment]
[I had an issue similar to this](https://github.com/revk/ESP32-Faikin/discussions/519).

My solution was to turn off the home assistant option on the Faikin, and then reenable it. That caused it to be shown again.

**Comment by con0aks** [comment]
Thanks for the advise.

Sadly I tried it already... didn't helped.

I also disabled mqtt and reenabled it after deleting all topics and restarting home assistant.
But also, no success.

**Comment by revk** [comment]
Can you confirm they do show on the web UI?

Have you tried restarting MQTT.

Try deleting the device from HA as well, and then restarting Faikin?

Finally in HA under MQTT you can get it to show what it received as the auto config, can you check that and post a copy.

**Comment by con0aks** [comment]
I can still see all values / sensors on the web interface.
Restarting MQTT and deleting the device in HA does not help.

But: When I disable and re-enable HA in the config of the faikin board I can shortly see the relevant topics for discovery but the configs of the missing sensors are empty.

I'm not exactly sure what you mean with your last point. Could you please explain it a little bit further.

Thanks in advice.

**Comment by revk** [comment]
HA let's you see the config that is announced.

Check that.

<img width="138" alt="Screenshot 2024-11-08 at 08 29 47" src="https://github.com/user-attachments/assets/9c7d6142-b031-4fc7-9ac8-a0c69fa4f91f">
<img width="319" alt="Screenshot 2024-11-08 at 08 29 53" src="https://github.com/user-attachments/assets/564a32ad-8ba1-4908-a0b7-978b8e3b3111">
<img width="143" alt="Screenshot 2024-11-08 at 08 30 00" src="https://github.com/user-attachments/assets/68f1d944-c072-49f4-8d98-49c8049bfa49">
<img width="158" alt="Screenshot 2024-11-08 at 08 31 22" src="https://github.com/user-attachments/assets/315eade0-952b-4af1-a78a-81205c337fa1">
<img width="334" alt="Screenshot 2024-11-08 at 08 31 29" src="https://github.com/user-attachments/assets/b1730f67-199b-4ef6-a1fc-57bf275270d2">
<img width="191" alt="Screenshot 2024-11-08 at 08 31 33" src="https://github.com/user-attachments/assets/1eec1998-f82a-46b3-aef9-3b0552ec79d5">
<img width="607" alt="Screenshot 2024-11-08 at 08 31 39" src="https://github.com/user-attachments/assets/168e276c-bb7b-4af0-9ed5-7c1f4bcff010">
<img width="576" alt="Screenshot 2024-11-08 at 08 31 49" src="https://github.com/user-attachments/assets/09521003-e571-449a-a56e-fb518b241e67">
<img width="526" alt="Screenshot 2024-11-08 at 08 31 59" src="https://github.com/user-attachments/assets/e5f229de-57d7-4fa2-93ae-631573882ca8">

**Comment by con0aks** [comment]
Ah, got it :)

Here are my results:
<img width="614" alt="Bildschirmfoto 2024-11-08 um 13 44 10" src="https://github.com/user-attachments/assets/ff9ebe0d-d07f-4cd2-8d36-6bda033ab6b2">
<img width="547" alt="Bildschirmfoto 2024-11-08 um 13 44 22" src="https://github.com/user-attachments/assets/a532c792-7752-4476-b82a-4dc43928e7f8">
<img width="573" alt="Bildschirmfoto 2024-11-08 um 13 44 35" src="https://github.com/user-attachments/assets/ec188061-49c0-485e-b1ff-e446e8493622">
<img width="584" alt="Bildschirmfoto 2024-11-08 um 13 44 45" src="https://github.com/user-attachments/assets/17bae1ea-78d2-4bfd-9407-383d6414c0b0">
<img width="595" alt="Bildschirmfoto 2024-11-08 um 13 44 58" src="https://github.com/user-attachments/assets/5c4708d5-d589-417a-93c5-d3c873bd80ff">

**Comment by revk** [comment]
OK that shows liquid.
You say the web shows the comp freq, and fan freq though?

**Comment by con0aks** [comment]
you are right:
Now the liquid sensor is present but the outside is gone...

Not exactly:
When the device is turned off: I can only see the temps.
When the device is turned on: I can additionally see the fan speed.

I cannot set the comp frequency on the web ui.

<img width="832" alt="Bildschirmfoto 2024-11-08 um 13 52 25" src="https://github.com/user-attachments/assets/74cf152f-8c54-4bf5-8e63-53ad1a463f17">
<img width="827" alt="Bildschirmfoto 2024-11-08 um 13 53 00" src="https://github.com/user-attachments/assets/d61790e4-709b-401b-ade4-5624fffa0cf7">

**Comment by revk** [comment]
Err, "cannot set the comp frequency", correct, there is no setting for that. There is a demand setting which has some impact.

This is all very odd.

**Comment by revk** [comment]
> Where did you saw that message?

Who, what message?

**Comment by con0aks** [comment]
"cannot set the comp frequency"

**Comment by con0aks** [comment]
Sry, got a little confused :D

**Comment by revk** [comment]
<img width="504" alt="Screenshot 2024-11-08 at 13 18 38" src="https://github.com/user-attachments/assets/82b38771-68b5-41d0-a0ef-78faffca1c39">

**Comment by revk** [comment]
Turn on `dump` setting and log the MQTT messages produced.

**Comment by revk** [comment]
Ok may be tomorrow when I check this.

**Comment by con0aks** [comment]
ok, thanks in advance.

**Comment by revk** [comment]
OK you are getting compressor. So I am wondering if it is a timing thing, HA config sent too soon before it has seen compressor, etc.

Ah, I worked it out, we changed to poll some things more slowly, and we do the HA config after the first poll, so some things not yet polled, D'Oh.

I'll make a beta release for you to test. Ready in a few minutes.

**Comment by con0aks** [comment]
Hey, I just upgraded the board to the new beta and now all five sensors are back in HA.

Thanks a lot for your rapid help!
