### ISSUE TITLE
Compatibility Question

### ISSUE THREAD

**Issue by jax8158** [revk/ESP32-Faikin#543]
I have a daikin air conditioner, model number FDXS12DVJU. I was wondering if it was compatible with the project? I am pretty new to this project and I don't quite understand so if someone could help me clarify before I spend a bunch of money to send this to America. Thanks for all help in advance! (Below I have included an image of the S21 Plug.) ![image](https://github.com/user-attachments/assets/3df18e02-ea5b-4ab2-9812-457ff8cebe72)

**Comment by reedy** [comment]
https://github.com/revk/ESP32-Faikin/wiki/List-of-confirmed-working-air-con-units does list `FDXS25EAVMB` and `FDXS50CVMB`, so it seems the same base `FDXS` might suggest you're in luck.

Is the S21 being currently used by the existing daikin wifi module?

**Comment by jax8158** [comment]
no, just the IR module that came with it, the reason why I want to use this is because the daikin wifi module is several hundred dollars.

**Comment by revk** [comment]
Can't guarantee it, but any model with S21 port should work with Faikin.
