### ISSUE TITLE
Dark mode / Dark LED mode

### ISSUE THREAD

**Issue by Hellslicer** [revk/ESP32-Faikin#547]
Dark mode setting is a shared setting between ESP32-Faikin and ESP32-RevK:
https://github.com/revk/ESP32-RevK/blob/4f306f114252e4bca53df71b21d3e296fdd5777b/revk.c#L1658-L1659
```c
   if (user || dark)
      return "K";
```
https://github.com/revk/ESP32-Faikin/blob/b2b323acadb250b16b3b1072d052e633d3608168/ESP/main/Faikin.c#L3438

Since https://github.com/revk/ESP32-RevK/commit/4f306f114252e4bca53df71b21d3e296fdd5777b + https://github.com/revk/ESP32-Faikin/commit/9dd4b0f513a712f2bb893eb6f0ea74966f303679, `live` flag is missing.

Can we either, add `live` flag to `dark` setting on ESP32-RevK, or add a new 'dedicated' dark setting on ESP32-Faikin?

**Comment by revk** [comment]
Hmm, I'll make `live`, sorry.
