### ISSUE TITLE
[BUG] GPIO connection to the board with usb-serial adapter

### ISSUE THREAD

**Issue by rici44** [revk/ESP32-Faikin#559]
**Faikin hardware**
[Amazon purchased](https://www.amazon.co.uk/dp/B0C2ZYXNYQ?ref=ppx_yo2ov_dt_b_fed_asin_title)

**Daikin hardware**
S21

**Describe the bug**
I bought 2pcs of your [faikin board ](https://www.amazon.co.uk/dp/B0C2ZYXNYQ?ref=ppx_yo2ov_dt_b_fed_asin_title)and tried to power it with a usb-serial board. [Setup manual](https://github.com/revk/ESP32-Faikin/blob/main/Manuals/Setup.md) does not shows [this version of the board](https://www.amazon.co.uk/dp/B0C2ZYXNYQ?ref=ppx_yo2ov_dt_b_fed_asin_title) which does not have gpio port as shown in the setup manual. 

_I need to power up the board and set up all necessary settings before connecting it to the Daikin. 
Could it be done? If so, how?_

**Expected behavior**
Working GPIO connection to the board.

**Comment by revk** [comment]
Sorry do you have a picture of the board?

**Comment by rici44** [comment]
> Sorry do you have a picture of the board?

Yes it is this board
<img width="747" alt="Screenshot 2024-11-21 at 14 22 25" src="https://github.com/user-attachments/assets/38258229-36a6-4508-9e3a-023b5a0f096a">
<img width="740" alt="Screenshot 2024-11-21 at 14 22 13" src="https://github.com/user-attachments/assets/5b7303f3-479e-4d6f-b218-2dc7ea6fc850">

**Comment by rici44** [comment]
> If WiFI details are not correct it creates and access point to allow you to set new details.

OK. thanks

**Comment by rici44** [comment]
> OK good, you can see the ⏚ and 12V as pins 5 and 4 on S21, power using those.

OK, thanks, powered up and running
