### ISSUE TITLE
"liquid" temperature sensor

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-Faikin#57]
In your code one of sensor variables is called "liquid" Why so and what does it mean ? I see in S21 protocol it's populated by 'SI' response; and in my opinion 'I' should stand for 'inlet', which you also have.

I have a guess that on some ACs there's an extra temperature sensor in the remote control, so that it feels more of the same temperature as a human would feel in the room. A traditional sensor in the indoor unit itself becomes "inlet".

My original BRP controller which i have also reports "hhum=-", which most likely stands for "home humidity". There's also a corresponding control on get_control_info, which reports "shum=0". I guess that's "set humidity". Looks like support for built-in humidifier in some top-grade models. Does this have to do with "liquid" ?

**Comment by njh** [comment]
I assume the "liquid" temperature is the temperature of the refrigerant liquid in the coil.

**Comment by revk** [comment]
I think it is.

**Comment by revk** [comment]
It I recall some models report “liquid” and “gas” temps. These are refrigerant. Inlet is the inlet air as I understand it.

**Comment by revk** [comment]
![image](https://github.com/revk/ESP32-Faikin/assets/996983/f91db341-2a93-4ed8-a5ac-96241e3e796e)

**Comment by Sonic-Amiga** [comment]
Thank you for explaining, IMHO worth mentioning  in docs somewhere (or wiki ?)
