### ISSUE TITLE
Not compatible with latest ESP IDF v5.1

### ISSUE THREAD

**Issue by ddv2005** [revk/ESP32-Faikin#66]
Hello,

I trying to build source code using latest ESP IDF v5.1 and found that it is not compatible. First, secure boot should be disabled via menu config. Second, sntp functions are deprecated and sntp_stop does not exist anymore. Now sntp functions should be with esp_ prefix, like esp_sntp_init, esp_sntp_stop and etc.
After these changes, I was able to build and flash the firmware normally.

**Comment by revk** [comment]
I have had issues with 5.1 (more than just the sntp stuff).

Please build with 5.0.1 for now, until they are addressed.

**Comment by revk** [comment]
OK 5.1 should build now.
