### ISSUE TITLE
Switching to ESPHome firmware

### ISSUE THREAD

**Issue by XMaarten** [revk/ESP32-Faikin#69]
Would it be possible to instead of upgrading to the latest firmware version, to upgrade to ESPHome instead?

I would like to use https://github.com/joshbenner/esphome-daikin-s21 instead of the default firmware with MQTT.

**Comment by revk** [comment]
MQTT `command/Faikin/upgrade https://someurl...` should allow you to fetch any binary.

Or use a lead to reflash directly.

**Comment by XMaarten** [comment]
Great, thanks! Maybe add this to the documentation, I couldn't find it myself.

**Comment by revk** [comment]
<img width="1043" alt="Screenshot 2023-07-08 at 13 02 06" src="https://github.com/revk/ESP32-Faikin/assets/996983/bfdd56b2-4e96-4188-962f-5d42c44d0ac8">

It is in the manual for the library it uses. https://github.com/revk/ESP32-RevK/blob/master/revk-user.md

**Comment by XMaarten** [comment]
I am getting a ESP_ERR_OTA_VALIDATE_FAILED error, probably because the image isn't signed? Is there a way to continue without a signed image?

**Comment by revk** [comment]
You would need to flash your own boot loader and image to start with. You can then decide if you want signed code or not, and set up your own signing.

I have not set "secure boot" fuses on the modules we sell, so the boot loader requires signing with *my* key, so flashing from scratch with your own code should be possible.

**Comment by revk** [comment]
You will need to do a serial flash for that.

But I am working on HomeKit/Matter stuff anyway, so hopefully won't be long before we have that.

Surely ESPHome binary would not talk to the Daikin though - would it?

**Comment by XMaarten** [comment]
When I have it flashed to a default ESPHome binary, I can flash it again using EPSHome itself to use https://github.com/joshbenner/esphome-daikin-s21 .  

Serial flash requires me to open the units, and I am always having problems with flashing serial.

**Comment by revk** [comment]
I suggest using https://www.amazon.co.uk/dp/B0C15K9ZC4

**Comment by XMaarten** [comment]
I wish I found that sooner :). 
Thanks, I just ordered one.

**Comment by revk** [comment]
Thanks, I am planning to put way more PCBs on Amazon soon.
