### ISSUE TITLE
SET button hidden since last update

### ISSUE THREAD

**Issue by andreground** [revk/ESP32-Faikin#71]
Hi,

Since last update, the "SET" button is disappeared on all the units.
Even forcing visibility through CSS, the values aren't updated after submit.

Please see attached screenshot.

<img width="323" alt="Screenshot 2023-07-09 alle 14 27 18" src="https://github.com/revk/ESP32-Faikin/assets/3788592/111f8b30-da1e-4dbd-a20d-a65a2d9f7102">

**Comment by revk** [comment]
Can you see if you have any errors in browser for web sockets?
The set vanishes if the websocket closes as the fields are sent via websocket.

If I can get an idea of the error I should be able to fix.

**Comment by andreground** [comment]
Here we are!

<img width="562" alt="Screenshot 2023-07-09 alle 23 02 42" src="https://github.com/revk/ESP32-Faikin/assets/3788592/c809127e-9c87-43e6-9f8a-26ac7556a8d4">

**Comment by revk** [comment]
Well, err, I don't suppose we know why? Working fine here... so a bit odd.

**Comment by andreground** [comment]
Hope this may help you fixing the issue.
It's really a mess because everything was working until the last update. I need to change the MQTT server, is there any workaround to apply this change meanwhile you fix the issue?

Thanks

<img width="275" alt="Screenshot 2023-07-09 alle 23 48 03" src="https://github.com/revk/ESP32-Faikin/assets/3788592/88f505f0-50ac-4155-8ef2-c07bca74c0da">

**Comment by iancoop** [comment]
I also found the set button had disappeared, but only from a web browser on my Mac. From the phone it was ok.

**Comment by revk** [comment]
Thanks for the feedback. I will investigate more this morning to sort this for you.

**Comment by revk** [comment]
OK, it did not have enough URLs... it should work now.

The upgrade button may work. If not, then a power cycle should force an auto upgrade within a couple of hours.

**Comment by revk** [comment]
I M going to restructure it, make the settings page the first URL and make it work even if no web sockets. Old school.

**Comment by revk** [comment]
I have done another issue, with a change to a simple form post now, should be more robust to future changes.
