### ISSUE TITLE
Faikin reports system is offline

### ISSUE THREAD

**Issue by HA-Ben** [revk/ESP32-Faikin#77]
Hi,

Just installed the Faikin module. Connects well to WiFi and can navigate to webpage.
Also MQTT is up and running to my HA instance.

When navigating to the Faikin homepage to control the airco I see under the under the controls:
System is off line
<img width="355" alt="offline" src="https://github.com/revk/ESP32-Faikin/assets/138382764/b4d6b792-e7ae-4969-a14f-cd7dbf6380b1">

Am I doing something wrong or is my air conditioner not compatible? 
I have connected the Faikin module to the S21 bus on the control board.
Model: FTX25K2V1B (2016)

Any ideas on how to fix this? Thank you for the support.

Bernard

**Comment by HA-Ben** [comment]
Just noticed another thread with same issue. Topic "FTXP25M5V1B9 no connection"
A few minutes ago it was confirmed Di-rk that the modified board with mosfet works :)
How can I get one? 
Thanks for the support

**Comment by revk** [comment]
I have some samples here, send me your address, I'm on mastodon at https://toot.me.uk/@RevK

**Comment by revk** [comment]
In the post

**Comment by HA-Ben** [comment]
Received the updated version and it works! Thank you for the quick support.

Bernard
