### ISSUE TITLE
Wifi hotspot not closed after connect to wifi network

### ISSUE THREAD

**Issue by Aldoszx** [revk/ESP32-Faikin#78]
I would like to spot this. 
After connecting to my wifi network, the Faikin AP is still visible on wifi networks list.
I think it should not be like that.
Also, in the serial console appears this error: 
(13100) httpd: httpd_server_init: error in listen (112)

Thank you !

**Comment by revk** [comment]
That is odd, it hangs around after initial config for around a minute, or should do. It definitely should not stay beyond that. It should not start the AP mode at all if there is a working wifi setting.

The error in listen is odd, have you updated to latest s/w?

**Comment by Aldoszx** [comment]
Yes, I have the latest version, installed today.
Also, I can't see the Powerful option and the icons are messed up mostly (see attached picture).
I have to mention that I am not connected to any AC. I'm only test the installation on ESP32-WROOM-32U board.
![faikin](https://github.com/revk/ESP32-Faikin/assets/8438064/97f39e3d-d2f8-407d-b4cf-4dc4337e66fb)

**Comment by Aldoszx** [comment]
> That is odd, it hangs around after initial config for around a minute, or should do. It definitely should not stay beyond that. It should not start the AP mode at all if there is a working wifi setting.
> 
> The error in listen is odd, have you updated to latest s/w?

After few tests, it seems that the AP is started after a reset but disappears after a couple of minutes.

**Comment by revk** [comment]
The AP should only start if the WiFi settings don't work. But I can test here to confirm.

The icons being wrong is very odd as that was fixed ages ago, it was just a character set setting in the http responses. Again, I can retest here to make sure it is right.

**Comment by Aldoszx** [comment]
Thank you for your answer !
Looking forward for updates !
I will came back later with feedback after I have all set and connected to my AC unit.
Best regards !

**Comment by revk** [comment]
I have checked here, definitely seeing `Content-Type: text/html;charset=utf-8` so icons should work.

Also definitely not seeing AP mode start after restart. You do have correct WiFi settings?

My current version is `2a856d5 2023-07-20T06:09:03` from `ota.revk.uk`

**Comment by Aldoszx** [comment]
I will try to access the web interface from another computer.
Did that and the problem with the icons also appears on two different computers on my network.
Indeed, from my iPhone the icons are shown correctly.
Regarding the AP, I have the correct wifi settings, the ESP connects to the network, but I can see the SSID on the computer where the ESP32 is connected to and also on my phone. It appears after the restart of the ESP32 and stays there for about 4-5 minutes or so.

![faikin_settings](https://github.com/revk/ESP32-Faikin/assets/8438064/dd26f7ad-9288-4b15-a22e-61f499434bd5)
![faikin_AP](https://github.com/revk/ESP32-Faikin/assets/8438064/fb207ae0-d3ee-4086-8d2c-b49dbb33caab)

Indeed, on another laptop I have in the same network, I cannot see the AP entry for Faikin.
I is strange !
Also, sometimes after restart, some fan modes icons disappears from web interface.
It comes back after a few page refresh.

![faikin2](https://github.com/revk/ESP32-Faikin/assets/8438064/7aaac4c1-7b8e-4839-abe1-111c2391dd8c)

**Comment by revk** [comment]
I suppose the icons could be your computer/browser lacking the current unicode symbols perhaps? The fact they appear as squares suggests maybe the utf-8 encoding is correct. In fact the ½ showing means it is utf-8. I can only assume a very old browser? The fact it shows from your iPhone probably means there is nothing really to "fix" here.

I still don't understand the AP appearing.

**Comment by Aldoszx** [comment]
I have the latest versions of Firefox, Edge and Chrome browsers, and I've tested on 3 computers, the result being the same ! 
Anyways, no big deal, just wanted to mention the issue. :)

**Comment by revk** [comment]
Does [Unicode power symbol](https://www.compart.com/en/unicode/U+23FB) work for you?

**Comment by Aldoszx** [comment]
Unfortunately, no !
![unicode](https://github.com/revk/ESP32-Faikin/assets/8438064/d9d7fab6-7f4c-4673-bfb7-d9aa93006c04)

**Comment by revk** [comment]
Ah, that is a clue. I mean that is unicode version 9.0 (June 2016), so only 7 years old, maybe your browser has not caught up.

**Comment by Aldoszx** [comment]
I don't know !
Or maybe, the font family used by my browsers are not compatible with this character.

**Comment by revk** [comment]
General unicode characters like these are not font family specific, i.e. fall back to generic emoji, etc.

**Comment by Aldoszx** [comment]
Yeah, but it it is strange that the character is not displayed correctly even on a fresh installed Win 11 computer.

**Comment by revk** [comment]
I'll consider changing to something different, but I really thought a standard character from 7 year old unicode would be fine, honest.

**Comment by Aldoszx** [comment]
I think you are right, but there are a lot of settings "around the world" that can not be compatible with your specific coding.
I would suggest using a picture instead of a symbol, maybe will be more compatible.

**Comment by revk** [comment]
Unicode is pretty universal - and 7 years is a long time - I am shocked that something so basic is not working. I think going back to the days of 1963 US-ASCII only and having GIF images for everything else would probably be a bad move.

**Comment by Aldoszx** [comment]
I don't know. Maybe you should set the text encoding as UTF-8 not unicode.

**Comment by revk** [comment]
Err, I have set to utf-8 (which is a way to encode unicode characters). I said that... It is working for the ½ unicode symbol!
<img width="709" alt="Screenshot 2023-07-20 at 12 27 09" src="https://github.com/revk/ESP32-Faikin/assets/996983/08aff744-f7f0-4ec1-b6e3-e8e68e9298f1">

**Comment by Aldoszx** [comment]
Indeed, it seems to be OK from your part !
One of my colleagues also tried from his phone, (an old Android 7.0) and has the same issue.
So...

**Comment by JeanOlivier** [comment]
> I have checked here, definitely seeing `Content-Type: text/html;charset=utf-8` so icons should work.
> 
> Also definitely not seeing AP mode start after restart. You do have correct WiFi settings?
> 
> My current version is `2a856d5 2023-07-20T06:09:03` from `ota.revk.uk`

FYI, I really don't mind, but icons have never worked for me on either of my 2 Faikin units, got the first one a few months ago. 

I also can't see the "powerful" option even when plugged on my unit with everything else working perfectly. I attributed that to a model-specific variation of the setting and just ignored it so far.

**Comment by revk** [comment]
Yes, `powerful` will only come up if we get the appropriate S21 responses.

If you think I have it wrong, please do get me some debug S21 for it, and how it changes with the remote control, and I'll change it. S21 is not something for which I can find any proper specification, which is a shame, it is all people like me reverse engineering. So it is quite possible there is a variant I don't know.

As for icons not working - I don't use windows or android and so did not know they had such a problem with basic unicode characters. I may see if I can find icons that work better. But I do things 7 years should be long enough for such icons to be deployed now, really.

**Comment by revk** [comment]
If you got on amazon, please do leave a review.

**Comment by JeanOlivier** [comment]
> If you got on amazon, please do leave a review.

I did, and it was glowing, but it was on your previous listing.
I'll check if I can leave a review on the new one even though I didn't "buy" this one specifically.

**Comment by revk** [comment]
Ah, yeh, Amazon messed me about on "brand" and would not allow an edit, so new listing, sorry about that.

**Comment by JeanOlivier** [comment]
No problem, I just left an honest review (aka glowing).
It might show as coming from an "unconfirmed buyer" though, because of the aforementioned.

**Comment by Aldoszx** [comment]
Maybe this could help, regarding power symbol:

https://unicodepowersymbol.com/font/

I had to install this font in order to see the symbol on Firefox, but in Chrome does not work.
It seems Windows does not have those fonts installed by default.
The embedded web fonts could be a solution.

**Comment by revk** [comment]
For a 7 year old unicode character, which should not even need a special font really, it seems crazy.

**Comment by Aldoszx** [comment]
I think that's right, but this is the true about windows

**Comment by Amtho** [comment]
To be fair the power symbol is also not working for me, but the rest :D. Version is compiled 20 days ago or so:
<img width="359" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/10643816/74a5b64d-8b42-45fd-845c-4a41595f16d4">

**Comment by revk** [comment]
I'll change to 0/1 for now, silly though.
