### ISSUE TITLE
Feature request - Remote reference with mqtt topic

### ISSUE THREAD

**Issue by davrodfer** [revk/ESP32-Faikin#80]
Hi. This is an awsome project.

I don't have any BlueCoinT BLE temperature sensor, but I have sensors around my house that I can use as temperature reference for the Faikin module.

I think it could be possible to put the module to listen to one mqtt topic and in this topic get the temperature readings of (by example) a zigbee temperature sensor.

Best regards.

**Comment by revk** [comment]
This should be in the manual. It does this already. I have sensors that provide the temperature via MQTT, and the target temperature.
