### ISSUE TITLE
Faikin reports system is offline

### ISSUE THREAD

**Issue by FrancescoFdd5** [revk/ESP32-Faikin#82]
Hi,

I have just installed the Faikin module, it connected successfully to the WiFi, and I can access the webpage without any issues.

However, when I access the page, it gives this error:

System is offline

I have two AC units, and both are behaving the same way:

FTXM25M2V1B
FTXM35M2V1B

Do you have any ideas on how to resolve this?

Thanks,
Francesco

![mstsc_Hvn6zFMAyL](https://github.com/revk/ESP32-Faikin/assets/12379812/1227cb35-45a1-40ef-8dde-8d413af0525d)

**Comment by revk** [comment]
Not listed on the "confirmed working" list. I wonder if they have the same 5V working issue.

Where are you located?

**Comment by revk** [comment]
That may not be a problem, but may want 5V working on Tx

**Comment by FrancescoFdd5** [comment]
How can I proceed? What tests can I perform to make it work?

**Comment by revk** [comment]
I suspect you need a slightly different circuit. I should have some next week, and could post out to you.

**Comment by NLNoID** [comment]
Hello, just installed my Faikin (received in NL through Amazon) and I have the same issue on a FTXM25R2V1B and FTXM35R2V1B. Could this be the same issue?

**Comment by revk** [comment]
It could be, and is one reason we have a list of known working units!

Once I have new ones with 5V Tx working, I can send some out.

Assuming this is the problem.

**Comment by FrancescoFdd5** [comment]
This could be great!

**Comment by NLNoID** [comment]
Yes, noted but figured that the when the FTXM20R2V1B is working (which is
on the list) the 25/35 would also work but unfortunately not it seems...

Op vr 28 jul. 2023 12:15 schreef RevK ***@***.***>:

**Comment by revk** [comment]
Expecting new boards end of next week.

**Comment by NLNoID** [comment]
Ok, thanks for the update.

Op vr 28 jul. 2023 12:30 schreef RevK ***@***.***>:

**Comment by Amtho** [comment]
Im using your Software on a FTXM20R2V1B without issues, however Im using my own board, schematics attached:
<img width="1754" alt="Unbenannt" src="https://github.com/revk/ESP32-Faikin/assets/10643816/39fc7335-2d51-4496-a8cc-49905342848a">

**Comment by revk** [comment]
Which rather suggests it is indeed unhappy with 3.3V tx, so new board should just work.

**Comment by revk** [comment]
I think a couple of people are waiting for replacements. I have some here now, just need address. DM me on https://toot.me.uk/@RevK
