### ISSUE TITLE
Disable automatic OTA updates

### ISSUE THREAD

**Issue by pfak** [revk/ESP32-Faikin#83]
> Note, automatic upgrade from ota.revk.uk is enabled. See instructions to make changes.

But the instructions do not seem to cover disabling OTA. I do not see any MQTT command to disable OTA.

Since I have a number of these units, I prefer to apply the updates in a controlled manner so if anything breaks I can deal with it.

**Comment by revk** [comment]
See [RevK library](https://github.com/revk/ESP32-RevK/blob/master/revk-user.md) Software updates...

**Comment by pfak** [comment]
Thank you @revk. It's not clear to look at another markdown file in a different Github repo, I looked at all the files in ESP32-Faikin repo, searching for OTA :(

**Comment by revk** [comment]
I'll add a note on it.
