### ISSUE TITLE
Compressor frequency sensor missing Home Assistant

### ISSUE THREAD

**Issue by pfak** [revk/ESP32-Faikin#84]
With the BRP module + Daikin component, I see the frequency for my compressor as an exposed entity.

I also see the JSON output under `status` in MQTT:

```
{"protocol":"S21¬Tx","online":true,"home":21.0,"heat":false,"fanrpm":730,"comp":300,"outside":26.5,"liquid":7.0,"power":true,"mode":"C","temp":18.5,"fan":"Q","swingh":false,"swingv":false,"autor":0.0,"autot":0.0,"auto0":"00:00","auto1":"00:00","autop":false}
```

However I do not see a corresponding entity in HomeAssistant:

![image](https://github.com/revk/ESP32-Faikin/assets/195072/dd6dc18a-32a2-4fbc-81e2-614c210552fd)

Is this expected? Is there a way to expose it to HomeAssistant?

**Comment by revk** [comment]
Should be easy enough. I don't suppose you know the HomeAssistance config for a compressor fan speed?

**Comment by pfak** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/daikin/sensor.py#L121

?

**Comment by pfak** [comment]
I think you need to divide by 10 on the integer you are reporting. I was at 30Hz according to my BRP adapters when I pasted the JSON.

**Comment by revk** [comment]
Hmm, the multiply by 10 may be something I have to configure. I'll have a look.

**Comment by revk** [comment]
OK, I am not set up to test HA right now, but have added.

Upgrade and see if that does what you need...

**Comment by apos-t** [comment]
I've upgraded to the new version and see new entities in ha, but without a value after 15min
<img width="346" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/109474219/e5ac17b2-3fdc-4a55-8c35-e29bd59be016">

**Comment by revk** [comment]
Ah, well spotted, I added to the config but did not send the values, oops. Try again.

**Comment by apos-t** [comment]
Comp is now available, but fan is still missing

**Comment by revk** [comment]
OK, we have a clash, as I have `fan` for the fan mode, and `fan` for speed. I'll change one. One moment.

**Comment by apos-t** [comment]
fanrpm and comprpm are now there - comprpm still fine. fanrpm stays at 0 should be 350 in my case

**Comment by revk** [comment]
Is the fan rpm reporting over MQTT correctly?

**Comment by revk** [comment]
OK, this would have been easier if I had set up an HA here, sorry. So a tad iterative as I don't have a test system here. Try again.

**Comment by apos-t** [comment]
no problem, looking good now 
<img width="480" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/109474219/dc5bc2b7-1234-407b-ae7d-19124399f9a4">

**Comment by revk** [comment]
Is 14rpm correct? I removed the *10 from the code, but 14rpm is very slow.

**Comment by apos-t** [comment]
you right should be 140, on an other unit on the same outside unit I see 140 in the mqtt logs.  If I understand it right the compressor is a value of the outside unit

**Comment by revk** [comment]
I'll reinstate the *10, same as the `fanrpm`. Making a release now.

**Comment by pfak** [comment]
Compressor is *Frequency* (Hz), not RPM. It should be `$Integer/10` for the correct value, and exposed as `UnitOfFrequency.HERTZ`,.

For example on the 4MXS36RMVJUA 4-head heat pump, the frequency (Hz) 15hz to 110hz:

![image](https://github.com/revk/ESP32-Faikin/assets/195072/e72aed60-4973-4e88-9cec-1882a0d275e1)

This output is from the BRP069B4x. Like the "Outdoor Temperature", it's an overall system value.

**Comment by revk** [comment]
OK, that is easy enough to sort, thanks. I'll do another release later today.

**Comment by revk** [comment]
OK new issue being made now.

**Comment by pfak** [comment]
Thank you ! The value is correct, however. Some changes to make it look proper in HA:

`comp`:

* `unit_of_meas` should be `Hz`
* `icon` should be `mdi:sine-wave`

`compfan`:

* `device_cla` does not need to be set (default in HA), and should NOT be `frequency` (so please unset)
* `icon` should be `mdi:fan`

Side note: I am slightly confused why `unit_of_meas`, and `device_cla` works even though it should be `unit_of_measurement` and `device_class`.

**Comment by revk** [comment]
I'll make that change, and yes all of the config names have a shorter form version as well.

**Comment by pfak** [comment]
Almost there.. Fan RPM is now a sine wave instead of a fan.

![image](https://github.com/revk/ESP32-Faikin/assets/195072/f3b692a3-4bc9-4722-8296-b78fd10c3a7b)

**Comment by revk** [comment]
Hmm, I am not setting icons for fan or temp, so maybe just telling it is Hz will get a sine wave. They are the same function at present, but I can change. I'll try with Hz and no icon first though - see if that is any good.

**Comment by pfak** [comment]
'fanrpm' is RPM, not Hz.

**Comment by revk** [comment]
Yes, I mean does it do sign wave for comp now or am I going to have to set icons for each?

**Comment by pfak** [comment]
Will check with your change in https://github.com/revk/ESP32-Faikin/commit/7433db7bfdc412c809cea0102b2bd49974806cad

**Comment by pfak** [comment]
![image](https://github.com/revk/ESP32-Faikin/assets/195072/88d6191d-98fa-4cec-965f-42e3cd499fb1)

Looks like you need to set icons for each. I think the sensors inherits the icon from the device? above it? maybe?? I noticed that the `climate` entry matches all the sensors, and IMO it is wrong, it should be `mdi:thermostat`.

So probably to stay within HA standards:

main device: `mdi:thermostat`
comp `mdi:sine-wave`
compfan `mdi:fan`
liquid `mdi:coolant-temperature`
outside `mdi:thermometer`.

**Comment by pfak** [comment]
Here's BRP device in HA:

![image](https://github.com/revk/ESP32-Faikin/assets/195072/68cf8143-2ca4-4a3f-a76b-27784e55b4d2)

Here's ecobee in HA:

![image](https://github.com/revk/ESP32-Faikin/assets/195072/edd3f6a3-3454-4cf5-b50d-81053f753ac9)

**Comment by pfak** [comment]
(Side note: Interesting that BRP can report 1/2 degree increments for outdoor temperature, but Faikin cannot?)

**Comment by revk** [comment]
Ok fine I'll work out icons.

**Comment by revk** [comment]
I am logging outside temp in ½ degrees, and reporting as such - is S21 only sending whole degrees I wonder?

**Comment by pfak** [comment]
All good now! Half degree shows too (I dont think you made any changes to this, I just see it now)

![image](https://github.com/revk/ESP32-Faikin/assets/195072/add81aa7-a389-409c-80cb-950dff41c57a)

**Comment by XMaarten** [comment]
> 'fanrpm' is RPM, not Hz.

This was mentioned a couple of times here, but I think it was missed :).

I am getting errors on startup about this:
`Entity sensor.fanrpm (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'rpm' which is not a valid unit for the device class ('frequency') it is using; expected one of ['MHz', 'GHz', 'Hz', 'kHz'];`

Can you please change unit_of_meas to Hz instead of rpm?

**Comment by revk** [comment]
Ok I'll have to change the name and about to be Hz then.

**Comment by revk** [comment]
OK new code issues, let me know if that makes sense.

**Comment by XMaarten** [comment]
> OK new code issues, let me know if that makes sense.

Yeah, that seems to work. I can see the new fanfreq value (11.5 Hz in low fan speed) in HomeAssistant. Thanks!

You could maybe consider to put all the entries below /homeassistant/sensor/ in a subcategory /homeassistant/sensor/faikin/ and name them using the device name instead of the mac address. So /homeassistant/sensor/faikin/aircolivingroom-blehum for example.  It works without any issues at the moment, but maybe more readable in MQTT itself.
