### ISSUE TITLE
Home Assistant 2023.8.0 changes

### ISSUE THREAD

**Issue by patrickli** [revk/ESP32-Faikin#87]
Upgraded to `2023.8.0` and there are a few warnings appearing in the log.

### not a valid preset mode

```
'{"online":true,"target":18.00,"temp":17.50,"outside":15.00,"liquid":19.50,"comp":0,"fanrpm":0,"mode":"off","fan":"auto","swing":"off","preset":"home"}' received on topic E89F6D31A200. 'home' is not a valid preset mode
```

This is because in the autodiscovery payload we have `'preset_modes': ['boost', 'normal']`, and `home` is not one of `boost` or `normal`. Either we need to add all modes into the autodiscovery or report a valid `preset`.

### fan speed unit

```
Entity sensor.fanrpm (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'rpm' which is not a valid unit for the device class ('frequency') it is using; expected one of ['MHz', 'kHz', 'GHz', 'Hz'];
```

Not sure how to fix this as there is no way to specify unit in autodiscovery payload. I will try to do a customize for the sensor and see if that fixes it.

### MQTT device name is equal to entity name in your config

This comes up as big repair warnings in the settings page.

<img width="622" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/502326/9354eb71-920f-4bd9-b040-28dc10200798">

In the discovery payload we have something like:

```
{
  "unique_id":"0C8B9596F510",
  "device":{
    "identifiers":[
      "0C8B9596F510"
    ],
    "name":"0C8B9596F510",
    "sw_version":"e084988",
    "manufacturer":"RevK",
    "configuration_url":"http://0C8B9596F510.local/"
  },
  "icon":"mdi:thermostat",
  "name":"0C8B9596F510",
  "min_temp":16.0,
  "max_temp":32.0,
  "temperature_command_topic":"command/0C8B9596F510/temp",
  "temperature_state_topic":"0C8B9596F510"
}
```

I think what it is complaining about is that the top level `name` value is the same as `device.name`. According to the documentation we should set the top level `name` to `null`.

**Comment by revk** [comment]
Will look now.

"Home" to "normal" was a silly mistake. Did not realise HA was so fussy.

**Comment by patrickli** [comment]
It certainly wasn't this fussy before.

**Comment by patrickli** [comment]
> Will look now.
> 
> "Home" to "normal" was a silly mistake. Did not realise HA was so fussy.
> 
> The other warnings I'm happy to take any advice on.

I don't have a good idea for fan RPM for now. For the last issue you can just set the top level `name` to `null` in the discovery payload.

**Comment by revk** [comment]
OK changed back to "home" now, do update.

If you have specific advice for changes for other warnings, please let me know and I will make changes.

As for `name`, just to clarify, this needs to be `"name":null` yes?

<img width="227" alt="Screenshot 2023-08-04 at 06 04 56" src="https://github.com/revk/ESP32-Faikin/assets/996983/1c302549-c980-4256-854c-de3d3c7c0d0a">

**Comment by patrickli** [comment]
Yes. not the one in `device`.

![image](https://github.com/revk/ESP32-Faikin/assets/502326/ceeffbad-361b-43c9-bb9b-a5f0b08b8033)

**Comment by revk** [comment]
And they definitely mean `null`, not simply omitting `"name":` ?

**Comment by patrickli** [comment]
That's what the doc says. So give that a try first.

**Comment by revk** [comment]
OK, issuing now with `"name":null`, let me know - I'm going to get breakfast.

**Comment by patrickli** [comment]
Ok the two issues has been resolved now. I'll have a think about the fan
rpm.

Also I noticed there are new "comp" sensor appeared. What does "comp"
stand for?

**Comment by revk** [comment]
Compressor.

**Comment by patrickli** [comment]
Some support readings regarding the change of name to null: https://www.hackster.io/news/home-assistant-2023-8-brings-new-mqtt-related-error-messages-but-don-t-worry-say-maintainers-bec84d16710e

**Comment by revk** [comment]
May be neater to omit it then.

**Comment by patrickli** [comment]
Closing the issue as can't do anything about the warning for unit of the fan. It is just a warning anyway.
