### ISSUE TITLE
wrong return of aircon/get_control_info

### ISSUE THREAD

**Issue by lorbetzki** [revk/ESP32-Faikin#89]
hello,

first of all i want to say thank you for this very cool device and sharing them. I ordered a couple of PCB and insert them on my ftxm25n2v1b and replace my brp069b41. 

I found an error after i sending aircon/get_control_info, i am missing a comma:

`ret=OK,pow=0,mode=3,adv=,stemp=22.0,shum=0,dt1=22.0,dt2=22.0,dt3=22.0,dt4=22.0,dt5=22.0,dt7=22.0,dh1=0,dh2=0,dh3=0,dh4=0,dh5=0,dh7=0dhh=0,b_mode=3,b_stemp=22.0,b_shum=0,alert=255,f_rate=A,f_dir=0,dfr1=0,dfr2=0,dfr3=0,dfr4=0,dfr5=0,dfr7=0,dfrh=0,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd7=0,dmdh=0,dmnd_run=0,en_demand=0
`
after "dh4=0,dh5=0,dh7=0" we need a "," then "dhh=0"

the next Problem is nearby the end. "dfd7=0,dmdh=0,dmnd_run=0", on my system i expect to find "dfd7=0,dfdh=0,dmnd_run=0".

from dmdh=0 to dfdh=0. Maybe you can confirm this.

Best regards

**Comment by revk** [comment]
This is all fudged to be backwards compatible, and clearly slightly wrong.

Fixed issue release - update and see if that is better.
