### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by staugaard** [revk/ESP32-Faikin#92]
Hey, This looks like an awesome module. I desperately need one. When are they available again?

**Comment by revk** [comment]
It is available now, on the UK Amazon store. Amazon do appear to ship to some other countries. But if all else fails there are forwarding companies that apparently work like https://www.forward2me.com

I used to have a note saying that on the listing but looks like Amazon actually removed it!

**Comment by staugaard** [comment]
Amazon tells me that it is unavailable

![image](https://github.com/revk/ESP32-Faikin/assets/4300/12fa5ae0-aae0-4e06-aaf3-bd49387ed261)

**Comment by staugaard** [comment]
I figured it out and placed an order to ship to New Zealand via forward2me.

**Comment by revk** [comment]
So for some reason they are not shipping to New Zealand. It is a mystery why they will ship some places some times and not others. Maybe ask Amazon. They have shipped to NZ before. Or use a forwarding company perhaps.

![image](https://github.com/revk/ESP32-Faikin/assets/996983/f521b97a-0fcc-498a-8bd3-b63c166ceee2)
