### ISSUE TITLE
FTX35KNV1B Reports System is Offline

### ISSUE THREAD

**Issue by jesusvallejo** [revk/ESP32-Faikin#96]
Hi, i just bought from amazon the module, i have set it up, but reports system is Offline. I manage to find #77 and #66 issues. Is it possible that i'm affected in the same way? I can solder, so in case there is a fix i could try to perform it. I'm also in possession of an  oscilloscope in case its of any help. Cheers

**Comment by revk** [comment]
Can you send picture of your module, so I can check which one it is.

**Comment by jesusvallejo** [comment]
![IMG20230818133105](https://github.com/revk/ESP32-Faikin/assets/20265725/dfdfa653-ac7a-4648-beff-14d04285ad3f)
![IMG20230818133458](https://github.com/revk/ESP32-Faikin/assets/20265725/08ef80b8-2425-4526-bd1e-274c81b57045)
Those are the best pictures i could take.

**Comment by revk** [comment]
OK, yes, they are the older model that does not do 5V working. Where in the world are you?

**Comment by jesusvallejo** [comment]
Spain, Madrid.

**Comment by revk** [comment]
Makes posting you a replacement a tad more expensive. Are you able to DM me on https://toot.me.uk/@RevK with your address.

**Comment by revk** [comment]
A new one is in the post so let me know if it does not work.

**Comment by jesusvallejo** [comment]
Received it and working. Thank you very much.

**Comment by revk** [comment]
Glad to hear it.
